### PR TITLE
feat(astro): Introduce `<Waitlist />` component

### PR DESCRIPTION
**Pull request by nikospapcom**
## Description

In this pr we're introducing `<Waitlist />` component for astro

## Checklist

- [ ] `pnpm test` runs as expected.
- [ ] `pnpm build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [x] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Comment by nikospapcom** [comment]
!snapshot

**Comment by nikospapcom** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @nikospapcom - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/astro | 1.5.0-snapshot.v20241125103044 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/astro`
```sh
npm i @clerk/astro@1.5.0-snapshot.v20241125103044 --save-exact
```

**Comment by nikospapcom** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @nikospapcom - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/astro | 1.5.0-snapshot.v20241125110854 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/astro`
```sh
npm i @clerk/astro@1.5.0-snapshot.v20241125110854 --save-exact
```

**Comment by panteliselef** [comment]
@nikospapcom don't we also need WaitList as a modal ?

**Comment by nikospapcom** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @nikospapcom - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/astro | 1.5.0-snapshot.v20241125153146 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/astro`
```sh
npm i @clerk/astro@1.5.0-snapshot.v20241125153146 --save-exact
```

**Review by wobsoriano — APPROVED** [review]
Looks good!

Re: WaitList as a modal @panteliselef - I don't think there's a separate WaitList modal component in `@clerk/clerk-react`, but they can use `$clerkStore.get().openWaitlist()` instead ❓

**Comment by nikospapcom** [comment]
> Looks good!
> 
> Re: WaitList as a modal @panteliselef - I don't think there's a separate WaitList modal component in `@clerk/clerk-react`, but they can use `$clerkStore.get().openWaitlist()` instead ❓

@wobsoriano we discussed offline with Pantelis and you're right, they can use `$clerkStore.get().openWaitlist()`

**Pull request merged**
