### PR TITLE
fix(backend): Replace `OrganizationMembershipRole` with custom types for authorization

### PR DESCRIPTION
**Pull request by panteliselef**
## Description
Backport of #2408 

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/backend`
- [ ] `@clerk/chrome-extension`
- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [ ] `@clerk/localizations`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/remix`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/themes`
- [ ] `@clerk/types`
- [ ] `build/tooling/chore`

### CODE REVIEW

**Comment by panteliselef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @panteliselef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/chrome-extension | 0.6.1-snapshot.vbc02cc0 |
| @clerk/clerk-js | 4.67.1-snapshot.vbc02cc0 |
| @clerk/clerk-expo | 0.19.26-snapshot.vbc02cc0 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@0.6.1-snapshot.vbc02cc0 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@4.67.1-snapshot.vbc02cc0 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@0.19.26-snapshot.vbc02cc0 --save-exact
```

**Comment by panteliselef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @panteliselef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 0.36.1-snapshot.vf6fc860 |
| @clerk/chrome-extension | 0.6.1-snapshot.vf6fc860 |
| @clerk/clerk-js | 4.67.1-snapshot.vf6fc860 |
| @clerk/clerk-expo | 0.19.26-snapshot.vf6fc860 |
| @clerk/fastify | 0.6.28-snapshot.vf6fc860 |
| gatsby-plugin-clerk | 4.4.30-snapshot.vf6fc860 |
| @clerk/nextjs | 4.28.2-snapshot.vf6fc860 |
| @clerk/remix | 3.1.12-snapshot.vf6fc860 |
| @clerk/clerk-sdk-node | 4.13.3-snapshot.vf6fc860 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/backend`
```sh
npm i @clerk/backend@0.36.1-snapshot.vf6fc860 --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@0.6.1-snapshot.vf6fc860 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@4.67.1-snapshot.vf6fc860 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@0.19.26-snapshot.vf6fc860 --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@0.6.28-snapshot.vf6fc860 --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@4.4.30-snapshot.vf6fc860 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@4.28.2-snapshot.vf6fc860 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@3.1.12-snapshot.vf6fc860 --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@4.13.3-snapshot.vf6fc860 --save-exact
```

**Review by anagstef — APPROVED** [review]

**Pull request merged**
