### PR TITLE
fix(clerk-js): Use first-party cookies when running on Cypress

### PR DESCRIPTION
**Pull request by anagstef**
### The issue:

Cypress discards third-party cookies. Also, it runs in an iframe. 
If we detect that clerk-js runs inside an iframe, we set our cookies with `SameSite: None` (third-party).
So, the following cookies never get set in the browser:
- `__session`
- `__client_uat`
- `__clerk_db_jwt`

### Proposed solution:

Cypress adds a global object on the window, on the `window.Cypress` property. We can exclude cookies getting set as third-party if we detect that the app runs inside Cypress.

## Checklist

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [x] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Comment by anagstef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @anagstef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/chrome-extension | 1.0.1-snapshot.v3a06a37 |
| @clerk/clerk-js | 5.1.0-snapshot.v3a06a37 |
| @clerk/clerk-expo | 1.0.1-snapshot.v3a06a37 |
| @clerk/fastify | 1.0.1-snapshot.v3a06a37 |
| gatsby-plugin-clerk | 5.0.0-beta.45 |
| @clerk/localizations | 2.1.0-snapshot.v3a06a37 |
| @clerk/nextjs | 5.0.2-snapshot.v3a06a37 |
| @clerk/clerk-react | 5.0.1-snapshot.v3a06a37 |
| @clerk/remix | 4.0.1-snapshot.v3a06a37 |
| @clerk/themes | 2.0.1-snapshot.v3a06a37 |
| @clerk/types | 4.1.0-snapshot.v3a06a37 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.0.1-snapshot.v3a06a37 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.1.0-snapshot.v3a06a37 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@1.0.1-snapshot.v3a06a37 --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@1.0.1-snapshot.v3a06a37 --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@5.0.0-beta.45 --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@2.1.0-snapshot.v3a06a37 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@5.0.2-snapshot.v3a06a37 --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@5.0.1-snapshot.v3a06a37 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.0.1-snapshot.v3a06a37 --save-exact
```
`@clerk/themes`
```sh
npm i @clerk/themes@2.0.1-snapshot.v3a06a37 --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@4.1.0-snapshot.v3a06a37 --save-exact
```

**Comment by anagstef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @anagstef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 1.0.1-snapshot.vbd3f75e |
| @clerk/chrome-extension | 1.0.1-snapshot.vbd3f75e |
| @clerk/clerk-js | 5.1.0-snapshot.vbd3f75e |
| @clerk/clerk-expo | 1.0.1-snapshot.vbd3f75e |
| @clerk/express | 0.0.2-snapshot.vbd3f75e |
| @clerk/fastify | 1.0.1-snapshot.vbd3f75e |
| gatsby-plugin-clerk | 5.0.0-beta.45 |
| @clerk/localizations | 2.1.0-snapshot.vbd3f75e |
| @clerk/nextjs | 5.0.2-snapshot.vbd3f75e |
| @clerk/clerk-react | 5.0.1-snapshot.vbd3f75e |
| @clerk/remix | 4.0.1-snapshot.vbd3f75e |
| @clerk/clerk-sdk-node | 5.0.1-snapshot.vbd3f75e |
| @clerk/testing | 1.0.0-snapshot.vbd3f75e |
| @clerk/themes | 2.0.1-snapshot.vbd3f75e |
| @clerk/types | 4.1.0-snapshot.vbd3f75e |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/backend`
```sh
npm i @clerk/backend@1.0.1-snapshot.vbd3f75e --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.0.1-snapshot.vbd3f75e --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.1.0-snapshot.vbd3f75e --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@1.0.1-snapshot.vbd3f75e --save-exact
```
`@clerk/express`
```sh
npm i @clerk/express@0.0.2-snapshot.vbd3f75e --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@1.0.1-snapshot.vbd3f75e --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@5.0.0-beta.45 --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@2.1.0-snapshot.vbd3f75e --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@5.0.2-snapshot.vbd3f75e --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@5.0.1-snapshot.vbd3f75e --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.0.1-snapshot.vbd3f75e --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@5.0.1-snapshot.vbd3f75e --save-exact
```
`@clerk/testing`
```sh
npm i @clerk/testing@1.0.0-snapshot.vbd3f75e --save-exact
```
`@clerk/themes`
```sh
npm i @clerk/themes@2.0.1-snapshot.vbd3f75e --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@4.1.0-snapshot.vbd3f75e --save-exact
```

**Comment by anagstef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @anagstef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/chrome-extension | 1.0.7-snapshot.v47a3ff9 |
| @clerk/clerk-js | 5.2.3-snapshot.v47a3ff9 |
| @clerk/clerk-expo | 1.0.7-snapshot.v47a3ff9 |
| gatsby-plugin-clerk | 5.0.0-beta.45 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.0.7-snapshot.v47a3ff9 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.2.3-snapshot.v47a3ff9 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@1.0.7-snapshot.v47a3ff9 --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@5.0.0-beta.45 --save-exact
```

**Review by dimkl — APPROVED** [review]

**Pull request merged**
