### PR TITLE
feat(nextjs,shared,backend,clerk-react): Introduce Protect for authorization (#2170)

### PR DESCRIPTION
**Pull request by panteliselef**
## Description

Backport of #2170. Please take a second to review and not approve it instantly

Since #2170 was merged, we have pushed a few changes that address issues from that PR.
All of them are included in this PR as well
- [fix(types): Update MembershipRole and OrganizationPermissionKey to not resolve to any](https://github.com/clerk/javascript/pull/2318)
- [fix(types,nextjs): Improve generated param type of auth().protect()](https://github.com/clerk/javascript/pull/2309)
- [fix(types): Typescript v5 cannot infer custom role types correctly](https://github.com/clerk/javascript/pull/2314)
- fix(types): [Avoid using ts-expect-error as it may fail for hosting apps ](https://github.com/clerk/javascript/pull/2313)
- [fix(clerk-react): Using wrong OrganizationCustomPermission type](https://github.com/clerk/javascript/pull/2310)

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/backend`
- [ ] `@clerk/chrome-extension`
- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [ ] `@clerk/localizations`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/remix`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/themes`
- [ ] `@clerk/types`
- [ ] `build/tooling/chore`

### CODE REVIEW

**Comment by panteliselef** [comment]
!snapshot

**Comment by panteliselef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @panteliselef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 0.36.0-snapshot.v7515d95 |
| @clerk/chrome-extension | 0.6.0-snapshot.v7515d95 |
| @clerk/clerk-js | 4.67.0-snapshot.v7515d95 |
| @clerk/clerk-expo | 0.19.25-snapshot.v7515d95 |
| @clerk/fastify | 0.6.27-snapshot.v7515d95 |
| gatsby-plugin-clerk | 4.4.29-snapshot.v7515d95 |
| @clerk/localizations | 1.26.13-snapshot.v7515d95 |
| @clerk/nextjs | 4.28.0-snapshot.v7515d95 |
| @clerk/clerk-react | 4.30.0-snapshot.v7515d95 |
| @clerk/remix | 3.1.11-snapshot.v7515d95 |
| @clerk/clerk-sdk-node | 4.13.2-snapshot.v7515d95 |
| @clerk/types | 3.60.0-snapshot.v7515d95 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/backend`
```sh
npm i @clerk/backend@0.36.0-snapshot.v7515d95 --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@0.6.0-snapshot.v7515d95 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@4.67.0-snapshot.v7515d95 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@0.19.25-snapshot.v7515d95 --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@0.6.27-snapshot.v7515d95 --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@4.4.29-snapshot.v7515d95 --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@1.26.13-snapshot.v7515d95 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@4.28.0-snapshot.v7515d95 --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@4.30.0-snapshot.v7515d95 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@3.1.11-snapshot.v7515d95 --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@4.13.2-snapshot.v7515d95 --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@3.60.0-snapshot.v7515d95 --save-exact
```

**Comment by panteliselef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @panteliselef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 0.36.0-snapshot.vf97a372 |
| @clerk/chrome-extension | 0.6.0-snapshot.vf97a372 |
| @clerk/clerk-js | 4.67.0-snapshot.vf97a372 |
| @clerk/clerk-expo | 0.19.25-snapshot.vf97a372 |
| @clerk/fastify | 0.6.27-snapshot.vf97a372 |
| gatsby-plugin-clerk | 4.4.29-snapshot.vf97a372 |
| @clerk/localizations | 1.26.13-snapshot.vf97a372 |
| @clerk/nextjs | 4.28.0-snapshot.vf97a372 |
| @clerk/clerk-react | 4.30.0-snapshot.vf97a372 |
| @clerk/remix | 3.1.11-snapshot.vf97a372 |
| @clerk/clerk-sdk-node | 4.13.2-snapshot.vf97a372 |
| @clerk/types | 3.60.0-snapshot.vf97a372 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/backend`
```sh
npm i @clerk/backend@0.36.0-snapshot.vf97a372 --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@0.6.0-snapshot.vf97a372 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@4.67.0-snapshot.vf97a372 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@0.19.25-snapshot.vf97a372 --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@0.6.27-snapshot.vf97a372 --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@4.4.29-snapshot.vf97a372 --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@1.26.13-snapshot.vf97a372 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@4.28.0-snapshot.vf97a372 --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@4.30.0-snapshot.vf97a372 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@3.1.11-snapshot.vf97a372 --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@4.13.2-snapshot.vf97a372 --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@3.60.0-snapshot.vf97a372 --save-exact
```

**Comment by panteliselef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @panteliselef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 0.36.0-snapshot.v1c96a9f |
| @clerk/chrome-extension | 0.6.0-snapshot.v1c96a9f |
| @clerk/clerk-js | 4.67.0-snapshot.v1c96a9f |
| @clerk/clerk-expo | 0.19.25-snapshot.v1c96a9f |
| @clerk/fastify | 0.6.27-snapshot.v1c96a9f |
| gatsby-plugin-clerk | 4.4.29-snapshot.v1c96a9f |
| @clerk/localizations | 1.26.13-snapshot.v1c96a9f |
| @clerk/nextjs | 4.28.0-snapshot.v1c96a9f |
| @clerk/clerk-react | 4.30.0-snapshot.v1c96a9f |
| @clerk/remix | 3.1.11-snapshot.v1c96a9f |
| @clerk/clerk-sdk-node | 4.13.2-snapshot.v1c96a9f |
| @clerk/types | 3.60.0-snapshot.v1c96a9f |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/backend`
```sh
npm i @clerk/backend@0.36.0-snapshot.v1c96a9f --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@0.6.0-snapshot.v1c96a9f --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@4.67.0-snapshot.v1c96a9f --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@0.19.25-snapshot.v1c96a9f --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@0.6.27-snapshot.v1c96a9f --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@4.4.29-snapshot.v1c96a9f --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@1.26.13-snapshot.v1c96a9f --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@4.28.0-snapshot.v1c96a9f --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@4.30.0-snapshot.v1c96a9f --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@3.1.11-snapshot.v1c96a9f --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@4.13.2-snapshot.v1c96a9f --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@3.60.0-snapshot.v1c96a9f --save-exact
```

**Comment by panteliselef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @panteliselef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 0.36.0-snapshot.v696bd7c |
| @clerk/chrome-extension | 0.6.0-snapshot.v696bd7c |
| @clerk/clerk-js | 4.67.0-snapshot.v696bd7c |
| @clerk/clerk-expo | 0.19.25-snapshot.v696bd7c |
| @clerk/fastify | 0.6.27-snapshot.v696bd7c |
| gatsby-plugin-clerk | 4.4.29-snapshot.v696bd7c |
| @clerk/localizations | 1.26.13-snapshot.v696bd7c |
| @clerk/nextjs | 4.28.0-snapshot.v696bd7c |
| @clerk/clerk-react | 4.30.0-snapshot.v696bd7c |
| @clerk/remix | 3.1.11-snapshot.v696bd7c |
| @clerk/clerk-sdk-node | 4.13.2-snapshot.v696bd7c |
| @clerk/types | 3.60.0-snapshot.v696bd7c |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/backend`
```sh
npm i @clerk/backend@0.36.0-snapshot.v696bd7c --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@0.6.0-snapshot.v696bd7c --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@4.67.0-snapshot.v696bd7c --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@0.19.25-snapshot.v696bd7c --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@0.6.27-snapshot.v696bd7c --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@4.4.29-snapshot.v696bd7c --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@1.26.13-snapshot.v696bd7c --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@4.28.0-snapshot.v696bd7c --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@4.30.0-snapshot.v696bd7c --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@3.1.11-snapshot.v696bd7c --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@4.13.2-snapshot.v696bd7c --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@3.60.0-snapshot.v696bd7c --save-exact
```

**Pull request merged**
