### PR TITLE
revert(backend): Introduce OrganizationPermissionAPI and OrganizationRoleAPI

### PR DESCRIPTION
**Pull request by panteliselef**
## Description

Revert "feat(backend): Introduce OrganizationRoleAPI [(#2178)](https://github.com/clerk/javascript/commit/23833adddf40aa2da746827dfac5ef4088f16f24) 

This reverts commit https://github.com/clerk/javascript/commit/b3a3dcdf4a8fa75c0dee4c55ab8fedebd49fdfd4

Revert "feat(backend): Introduce OrganizationPermissionAPI [(2177)](https://github.com/clerk/javascript/commit/0549d8ddafd0d54eac35bab812728c38101effc9) 

This reverts commit https://github.com/clerk/javascript/commit/0ce0edc283849a88b14b4b0df53b6858ed3a4f80

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/backend`
- [ ] `@clerk/chrome-extension`
- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [ ] `@clerk/localizations`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/remix`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/themes`
- [ ] `@clerk/types`
- [ ] `build/tooling/chore`

### CODE REVIEW

**Review by chanioxaris — APPROVED** [review]

**Review by dimkl — APPROVED** [review]

**Comment by tonjohn** [comment]
@panteliselef is there a timeline as to when these APIs will return?

I need them ASAP :(

**Comment by panteliselef** [comment]
Hey @tonjohn what are you trying to accomplish here ? We never shipped those because using the dashboard covers most of the cases.

**Comment by tonjohn** [comment]
We are generating the [ClerkAuthorization](https://clerk.com/docs/organizations/verify-user-permissions#how-to-add-types-for-roles-and-permissions) interface for improved DevEx (I'm happy to share this so that others can benefit).

We would also like to sync the data so that the same roles and permissions can be used across various pieces of our platform (for example a forum powered by Xenforo / Discourse).

Along those lines, webhooks related to roles and permissions would be nice 😅

**Comment by panteliselef** [comment]
Automatically creating those types is something we have considered in the past but got deprioritized. If this was available in the dashboard would that solve your problem ?

**Pull request merged**
