### PR TITLE
feat(testing): Introduce helpers for Playwright

### PR DESCRIPTION
**Pull request by anagstef**
## Description

This PR adds helpers to Playwright integration to easily sign-in and sign-out.

### `clerk.signIn`

The `clerk.signIn` helper is used to sign in a user using Clerk. This helper supports only the following first factor strategies:

- Password
- Phone code
- Email code

**Note:** Multi-factor authentication is not supported.

This helper internally uses the `setupClerkTestingToken`, so you don't need to call it separately.

**Prerequisites**

- You must call `page.goto` before calling this helper.
- Navigate to a non-protected page that loads Clerk before using this helper.

**Parameters**

- `opts.signInParams.strategy` - The sign in strategy. Supported strategies are 'password', 'phone_code' and 'email_code'.
- `opts.signInParams.identifier` - The user's identifier. Could be a username, a phone number or an email.
- `opts.signInParams.password` - The user's password. Required only if the strategy is 'password'.
- `opts.page` - The Playwright page object.
- `opts.setupClerkTestingTokenOptions` - The options for the `setupClerkTestingToken` function. Optional.

**Strategy Specifics**

- **Password:** The helper will sign in the user using the provided password and identifier.
- **Phone Code:** You must have a user with a test phone number as an identifier (e.g., `+15555550100`).
- **Email Code:** You must have a user with a test email as an identifier (e.g., `your_email+clerk_test@example.com`).

**Example**

```ts
import { clerk } from "@clerk/testing/playwright";

 test("sign in", async ({ page }) => {
    await page.goto("/");
    await clerk.signIn({
      page,
      signInParams: { strategy: 'phone_code', identifier: '+15555550100' },
    });
    await page.goto("/protected");
  });
```

### `clerk.signOut`

The `clerk.signOut` helper is used to sign out the current user using Clerk.

**Prerequisites**

- You must call `page.goto` before calling this helper.
- Navigate to a page that loads Clerk before using this helper.

**Parameters**

- `opts.signOutOptions` - A SignOutOptions object.
- `opts.page` - The Playwright page object.

**Example**

```ts
import { clerk } from "@clerk/testing/playwright";

 test("sign out", async ({ page }) => {
    await page.goto("/");
    await clerk.signIn({
      page,
      signInParams: { strategy: 'phone_code', identifier: '+15555550100' },
    });
    await page.goto("/protected");
    await clerk.signOut({ page });
    await page.goto("/protected");
    // should redirect to sign in page
  });
```

### `clerk.loaded`

The `clerk.loaded` helper asserts that Clerk has been loaded.

**Prerequisites**

- You must call `page.goto` before calling this helper.
- Navigate to a page that loads Clerk before using this helper.

## Checklist

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [x] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Comment by anagstef** [comment]
!snapshot

**Comment by anagstef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @anagstef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/chrome-extension | 1.2.4-snapshot.v8af4be3 |
| @clerk/clerk-js | 5.15.2-snapshot.v8af4be3 |
| @clerk/clerk-expo | 2.2.2-snapshot.v8af4be3 |
| @clerk/testing | 1.3.0-snapshot.v8af4be3 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.2.4-snapshot.v8af4be3 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.15.2-snapshot.v8af4be3 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@2.2.2-snapshot.v8af4be3 --save-exact
```
`@clerk/testing`
```sh
npm i @clerk/testing@1.3.0-snapshot.v8af4be3 --save-exact
```

**Comment by anagstef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @anagstef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/astro | 1.2.1-snapshot.v0d3816c |
| @clerk/chrome-extension | 1.2.4-snapshot.v0d3816c |
| @clerk/clerk-js | 5.16.0-snapshot.v0d3816c |
| @clerk/clerk-expo | 2.2.2-snapshot.v0d3816c |
| @clerk/testing | 1.3.0-snapshot.v0d3816c |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/astro`
```sh
npm i @clerk/astro@1.2.1-snapshot.v0d3816c --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.2.4-snapshot.v0d3816c --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.16.0-snapshot.v0d3816c --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@2.2.2-snapshot.v0d3816c --save-exact
```
`@clerk/testing`
```sh
npm i @clerk/testing@1.3.0-snapshot.v0d3816c --save-exact
```

**Comment by anagstef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @anagstef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/astro | 1.3.3-snapshot.v4222bf1 |
| @clerk/backend | 1.11.2-snapshot.v4222bf1 |
| @clerk/chrome-extension | 1.3.5-snapshot.v4222bf1 |
| @clerk/clerk-js | 5.21.3-snapshot.v4222bf1 |
| @clerk/elements | 0.15.3-snapshot.v4222bf1 |
| @clerk/clerk-expo | 2.2.11-snapshot.v4222bf1 |
| @clerk/express | 0.0.40-snapshot.v4222bf1 |
| @clerk/fastify | 1.0.42-snapshot.v4222bf1 |
| @clerk/localizations | 3.0.2-snapshot.v4222bf1 |
| @clerk/nextjs | 5.5.3-snapshot.v4222bf1 |
| @clerk/clerk-react | 5.8.3-snapshot.v4222bf1 |
| @clerk/remix | 4.2.26-snapshot.v4222bf1 |
| @clerk/clerk-sdk-node | 5.0.39-snapshot.v4222bf1 |
| @clerk/shared | 2.7.3-snapshot.v4222bf1 |
| @clerk/tanstack-start | 0.4.2-snapshot.v4222bf1 |
| @clerk/testing | 1.3.0-snapshot.v4222bf1 |
| @clerk/themes | 2.1.30-snapshot.v4222bf1 |
| @clerk/types | 4.20.2-snapshot.v4222bf1 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/astro`
```sh
npm i @clerk/astro@1.3.3-snapshot.v4222bf1 --save-exact
```
`@clerk/backend`
```sh
npm i @clerk/backend@1.11.2-snapshot.v4222bf1 --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.3.5-snapshot.v4222bf1 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.21.3-snapshot.v4222bf1 --save-exact
```
`@clerk/elements`
```sh
npm i @clerk/elements@0.15.3-snapshot.v4222bf1 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@2.2.11-snapshot.v4222bf1 --save-exact
```
`@clerk/express`
```sh
npm i @clerk/express@0.0.40-snapshot.v4222bf1 --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@1.0.42-snapshot.v4222bf1 --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@3.0.2-snapshot.v4222bf1 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@5.5.3-snapshot.v4222bf1 --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@5.8.3-snapshot.v4222bf1 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.2.26-snapshot.v4222bf1 --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@5.0.39-snapshot.v4222bf1 --save-exact
```
`@clerk/shared`
```sh
npm i @clerk/shared@2.7.3-snapshot.v4222bf1 --save-exact
```
`@clerk/tanstack-start`
```sh
npm i @clerk/tanstack-start@0.4.2-snapshot.v4222bf1 --save-exact
```
`@clerk/testing`
```sh
npm i @clerk/testing@1.3.0-snapshot.v4222bf1 --save-exact
```
`@clerk/themes`
```sh
npm i @clerk/themes@2.1.30-snapshot.v4222bf1 --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@4.20.2-snapshot.v4222bf1 --save-exact
```

**Review by wobsoriano — APPROVED** [review]
🧪 👏 awesome

**Review by octoper — APPROVED** [review]

**Pull request merged**
