### PR TITLE
feat(localizations): Update translations for multiple languages

### PR DESCRIPTION
**Pull request by NavidJalilian**
This pull request includes updates to the language files for various locales in Clerk. These updates aim to improve the accuracy and consistency of translations for multiple languages, ensuring a better user experience across different regions.

The languages updated in this PR include:

1. French (FR)
2. German (DE)
3. Spanish (ES)
4. Italian (IT)
5. Dutch (NL)
6. Portuguese (PT)
7. Turkish (TR)

Changes Introduced:

- Updated translation files for each of the aforementioned languages, including user-facing strings in authentication and user account management flows.
- Consistency improvements for some existing translations and more precise language usage to match the application's tone and context.

How to Test:

1. Pull the changes from this branch into your local development environment.
2. Verify the translations in the UI for each of the affected languages.
3. Ensure that the placeholders, form field hints, and other UI text display correctly in each language.
4. Test language switching functionality to ensure all new translations are being used properly. You can manually switch the UI language to check the correctness of the translations in each language file.

## Checklist

- [x]  `pnpm test` runs as expected.
- [x]  `pnpm build` runs as expected.
- [ ]  (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ]  (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ]  🐛 Bug fix
- [x]  🌟 New feature (Localization updates)
- [ ]  🔨 Breaking change
- [ ]  📖 Refactoring / dependency upgrade / documentation
- [ ]  other:

### CODE REVIEW

**Comment by NavidJalilian** [comment]
Hi, I'm having trouble with the language updates in this PR. Could someone please assist with debugging this? Any pointers on how to approach the issue would be much appreciated! @tmilewski  @kylemac  @dstaley

**Comment by tmilewski** [comment]
> Hi, I'm having trouble with the language updates in this PR. Could someone please assist with debugging this? Any pointers on how to approach the issue would be much appreciated! @tmilewski @kylemac @dstaley

@NavidJalilian Thank you for the PR! Give me a few, and I'll be able to take a look. Please note that, once approved to run in CI, the integration tests will fail and that's expected.

**Comment by NavidJalilian** [comment]
Hi @tmilewski, just wanted to check if there's anything else needed from my side to help move this PR forward? Happy to make any necessary adjustments.

**Comment by tmilewski** [comment]
@NavidJalilian I made some small updates, but this looks good-to-go. Thank you!

**Review by tmilewski — APPROVED** [review]

**Pull request merged**
