### PR TITLE
feat(express): Make `requireAuth` middleware flexible

### PR DESCRIPTION
**Pull request by wobsoriano**
## Description

This pull request modifies the `requireAuth` middleware to return a custom `UnauthorizedError` via `next()` instead of throwing a 401 directly. The core change:

```ts
// Before
if (!getAuth(request).userId) {
  return response.status(401).send('Unauthorized');
}

// After
if (!getAuth(request).userId) {
  return next(new UnauthorizedError());
}
```

This aligns the `requireAuth` middleware with Express [error handling patterns](https://expressjs.com/en/guide/error-handling.html) and makes it customizable. Userland can now configure their own error handling middleware to process the `UnauthorizedError` as needed. Here's an example:

```ts
import { clerkMiddleware, requireAuth, UnauthorizedError } from '@clerk/express'

const app = express()
app.use(clerkMiddleware())

app.get('/protected', requireAuth, (req, res) => {
  res.send('This is a protected route')
})

app.use((err, req, res, next) => {
 if (err instanceof UnauthorizedError) {
   res.status(401).send('Unauthorized')
 } else {
   next(err)
 }
})
```

_This is part of making our Express SDK ready._

Resolves ECO-190

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [x] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [X] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Review by octoper — APPROVED** [review]
🔥

**Review by panteliselef — CHANGES_REQUESTED** [review]
I'm confused by this a bit.

Can't devs already do this, just by creating their own error class ?
Also should we expose a ForbiddenError?

From the first look, this seems like a utility that should've been provided from the framework itself.

**Review by tmilewski — APPROVED** [review]
Looks good, but I defer to Pantelis...

**Comment by wobsoriano** [comment]
Hi @panteliselef! To answer your questions:

> Can't devs already do this, just by creating their own error class ? 

You're right that devs could create their own error classes. However, this PR addresses the concern in the ticket about `requireAuth` [sending a fixed 401 response](https://github.com/clerk/javascript/blob/d0960c45a94aa9125acfee464070c72a1898a2f3/packages/express/src/requireAuth.ts#L34) with no way of customizing it. I believe they won't be able to catch the fixed response if they create a custom class and catch it inside an error-handling middleware. The key difference with our custom `UnauthorizedError` class is about flow control and flexibility in the middleware chain. 

Another suggestion from Jeff (❓) in the ticket was to make `requireAuth` accept a callback, but I still went with custom error class to align with Express error-handling patterns and it's extensible.

> Also should we expose a ForbiddenError?

Is your suggestion about `ForbiddenError` related to permission checks? If so, then yes, we could definitely export that class too (even though we don't have a helper middleware like `requireAuth` that sends a class like `UnauthorizedError`).

**Comment by panteliselef** [comment]
@wobsoriano Yes Forbidden would be about roles & permissions. I'm not familiar with our express sdk. But someone can use `has()` or a flow control utility that would result in a 403, having this error seems useful.

**Review by panteliselef — APPROVED** [review]
Great work

**Comment by wobsoriano** [comment]
> @wobsoriano Yes Forbidden would be about roles & permissions. I'm not familiar with our express sdk. But someone can use `has()` or a flow control utility that would result in a 403, having this error seems useful.

Added! Also I didn't see it, but we actually do the same thing with `@clerk/clerk-sdk-node` here:

https://github.com/clerk/javascript/blob/d0960c45a94aa9125acfee464070c72a1898a2f3/packages/sdk-node/src/clerkExpressRequireAuth.ts#L48

and we're planning to deprecate `@clerk/clerk-sdk-node` too to remove maintenance burden between them

**Comment by wobsoriano** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @wobsoriano - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/astro | 1.3.3-snapshot.v40851e4 |
| @clerk/backend | 1.12.0-snapshot.v40851e4 |
| @clerk/chrome-extension | 1.3.5-snapshot.v40851e4 |
| @clerk/clerk-js | 5.22.0-snapshot.v40851e4 |
| @clerk/elements | 0.15.3-snapshot.v40851e4 |
| @clerk/clerk-expo | 2.2.11-snapshot.v40851e4 |
| @clerk/express | 0.1.0-snapshot.v40851e4 |
| @clerk/fastify | 1.0.42-snapshot.v40851e4 |
| @clerk/localizations | 3.0.2-snapshot.v40851e4 |
| @clerk/nextjs | 5.5.3-snapshot.v40851e4 |
| @clerk/clerk-react | 5.9.0-snapshot.v40851e4 |
| @clerk/remix | 4.2.26-snapshot.v40851e4 |
| @clerk/clerk-sdk-node | 5.0.39-snapshot.v40851e4 |
| @clerk/shared | 2.8.0-snapshot.v40851e4 |
| @clerk/tanstack-start | 0.4.2-snapshot.v40851e4 |
| @clerk/testing | 1.2.22-snapshot.v40851e4 |
| @clerk/themes | 2.1.30-snapshot.v40851e4 |
| @clerk/types | 4.21.0-snapshot.v40851e4 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/astro`
```sh
npm i @clerk/astro@1.3.3-snapshot.v40851e4 --save-exact
```
`@clerk/backend`
```sh
npm i @clerk/backend@1.12.0-snapshot.v40851e4 --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.3.5-snapshot.v40851e4 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.22.0-snapshot.v40851e4 --save-exact
```
`@clerk/elements`
```sh
npm i @clerk/elements@0.15.3-snapshot.v40851e4 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@2.2.11-snapshot.v40851e4 --save-exact
```
`@clerk/express`
```sh
npm i @clerk/express@0.1.0-snapshot.v40851e4 --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@1.0.42-snapshot.v40851e4 --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@3.0.2-snapshot.v40851e4 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@5.5.3-snapshot.v40851e4 --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@5.9.0-snapshot.v40851e4 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.2.26-snapshot.v40851e4 --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@5.0.39-snapshot.v40851e4 --save-exact
```
`@clerk/shared`
```sh
npm i @clerk/shared@2.8.0-snapshot.v40851e4 --save-exact
```
`@clerk/tanstack-start`
```sh
npm i @clerk/tanstack-start@0.4.2-snapshot.v40851e4 --save-exact
```
`@clerk/testing`
```sh
npm i @clerk/testing@1.2.22-snapshot.v40851e4 --save-exact
```
`@clerk/themes`
```sh
npm i @clerk/themes@2.1.30-snapshot.v40851e4 --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@4.21.0-snapshot.v40851e4 --save-exact
```

**Pull request merged**
