### PR TITLE
fix(nextjs): Replace router.refresh() with cookies().delete()

### PR DESCRIPTION
**Pull request by nikosdouvlis**
## Description

In this PR we replace `router.refresh` with a server action that calls `cookies().delete`. According to the [NextJS docs](https://nextjs.org/docs/app/building-your-application/caching), using the `cookies().delete` API invalidates the FE client cache, similar to what `router.refresh` does.

The main difference between the two is that `router.refresh` will then attempt to fetch and re-mount the current page. This causes our components to unmount and mount again, losing state before `setActive` completes. This usually leads to navigation/redirect issues, issues completing oauth flows etc. 

Caveat: 
We can only use server action directly for next@14 and above, as server actions were an experimental feature in next@13.
For next@13 we still call `router.refresh`. Users that are on next@13 should upgrade to at least `next@14` if they notice any of the issues described above.

## Checklist

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Comment by joysamaddar** [comment]
Hi @nikosdouvlis,
Hope you are having a good day.
Is this PR related to fixing the issue where in NextJS, the page gets reloaded once we signout and hence clerk is not redirecting to "/" route instead reloading the same route which redirects us to the signin page with the fallback of the current route?

**Comment by clerk-cookie** [comment]
Hey @desiprisg - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 1.2.2-snapshot.v958fab4 |
| @clerk/chrome-extension | 1.0.17-snapshot.v958fab4 |
| @clerk/clerk-js | 5.6.0-snapshot.v958fab4 |
| @clerk/elements | 0.6.0-snapshot.v958fab4 |
| @clerk/clerk-expo | 1.2.0-snapshot.v958fab4 |
| @clerk/express | 0.0.11-snapshot.v958fab4 |
| @clerk/fastify | 1.0.13-snapshot.v958fab4 |
| gatsby-plugin-clerk | 5.0.0-beta.45 |
| @clerk/localizations | 2.4.4-snapshot.v958fab4 |
| @clerk/nextjs | 5.1.4-snapshot.v958fab4 |
| @clerk/clerk-react | 5.2.3-snapshot.v958fab4 |
| @clerk/remix | 4.1.0-snapshot.v958fab4 |
| @clerk/clerk-sdk-node | 5.0.10-snapshot.v958fab4 |
| @clerk/shared | 2.2.2-snapshot.v958fab4 |
| @clerk/testing | 1.1.6-snapshot.v958fab4 |
| @clerk/themes | 2.1.9-snapshot.v958fab4 |
| @clerk/types | 4.6.0-snapshot.v958fab4 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/backend`
```sh
npm i @clerk/backend@1.2.2-snapshot.v958fab4 --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.0.17-snapshot.v958fab4 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.6.0-snapshot.v958fab4 --save-exact
```
`@clerk/elements`
```sh
npm i @clerk/elements@0.6.0-snapshot.v958fab4 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@1.2.0-snapshot.v958fab4 --save-exact
```
`@clerk/express`
```sh
npm i @clerk/express@0.0.11-snapshot.v958fab4 --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@1.0.13-snapshot.v958fab4 --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@5.0.0-beta.45 --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@2.4.4-snapshot.v958fab4 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@5.1.4-snapshot.v958fab4 --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@5.2.3-snapshot.v958fab4 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.1.0-snapshot.v958fab4 --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@5.0.10-snapshot.v958fab4 --save-exact
```
`@clerk/shared`
```sh
npm i @clerk/shared@2.2.2-snapshot.v958fab4 --save-exact
```
`@clerk/testing`
```sh
npm i @clerk/testing@1.1.6-snapshot.v958fab4 --save-exact
```
`@clerk/themes`
```sh
npm i @clerk/themes@2.1.9-snapshot.v958fab4 --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@4.6.0-snapshot.v958fab4 --save-exact
```

**Comment by nikosdouvlis** [comment]
> Hi @nikosdouvlis, Hope you are having a good day. Is this PR related to fixing the issue where in NextJS, the protected page gets server reloaded once we press signout and hence clerk is not redirecting to the sign out route instead reloads the same route which redirects us to the signin page with the fallback of the current route?

Hello @joysamaddar , I hope you're having a great day as well :) 
Even though I am not completely sure yet, as this fix was intended to solve a different issue, the underlying root cause does look like it's the same, so I'm fairly confident that this will resolve the issue you describe. That being said, more testing needs to be done on our end! 

Would you mind sharing a GH issue that describes your problem in detail, if there is one? Happy to take a look.

**Comment by joysamaddar** [comment]
> > Hi @nikosdouvlis, Hope you are having a good day. Is this PR related to fixing the issue where in NextJS, the protected page gets server reloaded once we press signout and hence clerk is not redirecting to the sign out route instead reloads the same route which redirects us to the signin page with the fallback of the current route?
> 
> Hello @joysamaddar , I hope you're having a great day as well :) Even though I am not completely sure yet, as this fix was intended to solve a different issue, the underlying root cause does look like it's the same, so I'm fairly confident that this will resolve the issue you describe. That being said, more testing needs to be done on our end!
> 
> Would you mind sharing a GH issue that describes your problem in detail, if there is one? Happy to take a look.

Hello again,
I tried out the snapshot version of this PR and it seems this fixed the issue i described.
Do you still want me to make an issue for this? Happy to do so if it helps.

**Review by anagstef — APPROVED** [review]
💯

**Review by panteliselef — APPROVED** [review]
🚢

**Review by dimkl — APPROVED** [review]

**Pull request merged**
