### PR TITLE
chore(localizations): `nl-NL` updates

### PR DESCRIPTION
**Pull request by guustgoossens**
## Checklist

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [x] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Comment by guustgoossens** [comment]
@alexcarpenter I kept running into package-lock.json problems in the other PR, so I made a new one. Is this one valid?

**Comment by tmilewski** [comment]
@guustgoossens It seems that it's not building due to a type error. Mind checking that out? Thanks a lot! 

```
Error: src/nl-NL.ts(741,9): error TS2561: Object literal may only specify known properties, but 'messageLine2' does not exist in type 'DeepPartial<{ title: string; messageLine1: string; }>'. Did you mean to write 'messageLine1'?
```

**Review by tmilewski — CHANGES_REQUESTED** [review]
@guustgoossens It seems that it's not building due to a type error. Mind checking that out? Thanks a lot! 

```
Error: src/nl-NL.ts(741,9): error TS2561: Object literal may only specify known properties, but 'messageLine2' does not exist in type 'DeepPartial<{ title: string; messageLine1: string; }>'. Did you mean to write 'messageLine1'?
```

**Comment by guustgoossens** [comment]
> @guustgoossens It seems that it's not building due to a type error. Mind checking that out? Thanks a lot!
> 
> ```
> Error: src/nl-NL.ts(741,9): error TS2561: Object literal may only specify known properties, but 'messageLine2' does not exist in type 'DeepPartial<{ title: string; messageLine1: string; }>'. Did you mean to write 'messageLine1'?
> ```

should work now!

**Review by tmilewski — APPROVED** [review]

**Review by tmilewski — APPROVED** [review]

**Pull request merged**
