### PR TITLE
fix(clerk-js): Removed animation for active devices

### PR DESCRIPTION
**Pull request by octoper**
## Description

This PR removes the animation from the active devices section in the `<UserProfile/>`.

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Review by desiprisg — CHANGES_REQUESTED** [review]
I don't think this prop makes sense. You can just remove the wrapper.

**Comment by desiprisg** [comment]
Props should not be on `<Animated />`. We should just remove the wrapper when we don't want animations to take place.

**Comment by octoper** [comment]
Yeah but `<Animated/>` here is used inside `<ProfileSection.ItemList/>` which is used in multiple places, we only want the animation gone for the Active Devices.

**Comment by anagstef** [comment]
!preview

**Comment by clerk-cookie** [comment]
Hey @anagstef, your preview is currently deploying and should be available shortly.

| Status | Preview | Updated (UTC) |
| :-- | :-- | :-- |
| :cook: _Deploying..._ | [Inspect](https://javascript-preview-gz4ke9hz7.clerkstage.dev) | Feb 19, 2024 09:33 AM |

**Review by desiprisg — COMMENTED** [review]
💯

**Pull request merged**
