### PR TITLE
fix(chrome-extension): Appropriately handle fulfilled, but null, cookie promises

### PR DESCRIPTION
**Pull request by tmilewski**
## Description

Depending on certain setups, we were receiving fulfulled, but null, promises. This updates that check.

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Comment by clerk-cookie** [comment]
Hey @tmilewski - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/astro | 1.0.2-snapshot.v6146fa5 |
| @clerk/chrome-extension | 1.1.6-snapshot.v6146fa5 |
| @clerk/clerk-js | 5.10.1-snapshot.v6146fa5 |
| @clerk/clerk-expo | 1.2.9-snapshot.v6146fa5 |
| gatsby-plugin-clerk | 5.0.0-beta.45 |
| @clerk/localizations | 2.5.1-snapshot.v6146fa5 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/astro`
```sh
npm i @clerk/astro@1.0.2-snapshot.v6146fa5 --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.1.6-snapshot.v6146fa5 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.10.1-snapshot.v6146fa5 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@1.2.9-snapshot.v6146fa5 --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@5.0.0-beta.45 --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@2.5.1-snapshot.v6146fa5 --save-exact
```

**Review by royanger — APPROVED** [review]
Working for customer who reported the issue.

**Comment by dimkl** [comment]
@tmilewski Why do we need this change? What does this affect? Was there an issue that this change fixes?

**Comment by tmilewski** [comment]
@dimkl It just affects the Chrome Extension. One person was seeing issues with a misconfigured manifest alongside a dev-in-prod scenario, this helps to mitigate that.

**Pull request merged**
