### PR TITLE
fix(chrome-extension): Remove Origin from API mutation request headers

### PR DESCRIPTION
**Pull request by tmilewski**
## Description

Mutation requests (think: sign out) would fail as the API doesn't allow for origin and authorization to be set at the same time.

Fixes SDK-1736

## Checklist

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [x] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Comment by tmilewski** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @tmilewski - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/chrome-extension | 1.0.8-snapshot.v7aec5a2 |
| @clerk/clerk-js | 5.2.4-snapshot.v7aec5a2 |
| @clerk/clerk-expo | 1.0.8-snapshot.v7aec5a2 |
| gatsby-plugin-clerk | 5.0.0-beta.45 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.0.8-snapshot.v7aec5a2 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.2.4-snapshot.v7aec5a2 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@1.0.8-snapshot.v7aec5a2 --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@5.0.0-beta.45 --save-exact
```

**Review by royanger — APPROVED** [review]
The snapshot resolved the errors I was seeing.

**Review by LekoArts — APPROVED** [review]

**Comment by dimkl** [comment]
@tmilewski, @royanger  Why is the case only for mutation requests? What is the error making the requests fail?
Did you have the allowed_origins setup for the instance?

**Comment by tmilewski** [comment]
@dimkl The long-and-short of it is that it was only happening for mutation requests, and yes `allowed_origins` was set up. 

After a bit of testing it was determined that while `allowed_origins` was set up, the issue was more that the id of the extension had changed, likely with an uninstall/reinstall without a stable/unique id.

This, ultimately, wound up becoming an artifact of testing and had no effect on the end result. As such it didn't need to be approved/merged.

**Pull request merged**
