### PR TITLE
fix(clerk-js): Avoid sending password when saml is enabled

### PR DESCRIPTION
**Pull request by panteliselef**
### Video with the fixed flows
https://www.loom.com/share/54775174c83d4a23a00fda669789848b?sid=6149812c-9df7-43f1-b896-400c138b4791

This PR addresses an issue with our SignIn component due to the existence of the hidden password field.

Stale information in password managers would autofill email + password for email addresses that require SAML to be used. In that scenario, FAPi would return an field error that was not displayed in the component, causing frustration to end users that could not logged in.

The solution is to "detect" the intention of the end user, and quickly recover from it by signing them in, with password or with SAML.

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Comment by tmilewski** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @tmilewski - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/chrome-extension | 1.0.19-snapshot.vcc64bf8 |
| @clerk/clerk-js | 5.7.1-snapshot.vcc64bf8 |
| @clerk/elements | 0.8.0-snapshot.vcc64bf8 |
| @clerk/clerk-expo | 1.2.2-snapshot.vcc64bf8 |
| gatsby-plugin-clerk | 5.0.0-beta.45 |
| @clerk/remix | 4.1.2-snapshot.vcc64bf8 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.0.19-snapshot.vcc64bf8 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.7.1-snapshot.vcc64bf8 --save-exact
```
`@clerk/elements`
```sh
npm i @clerk/elements@0.8.0-snapshot.vcc64bf8 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@1.2.2-snapshot.vcc64bf8 --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@5.0.0-beta.45 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.1.2-snapshot.vcc64bf8 --save-exact
```

**Review by tmilewski — APPROVED** [review]

**Comment by panteliselef** [comment]
!snapshot

**Review by nikosdouvlis — APPROVED** [review]

**Comment by panteliselef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @panteliselef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/chrome-extension | 1.0.19-snapshot.v3470a88 |
| @clerk/clerk-js | 5.7.1-snapshot.v3470a88 |
| @clerk/elements | 0.8.0-snapshot.v3470a88 |
| @clerk/clerk-expo | 1.2.2-snapshot.v3470a88 |
| gatsby-plugin-clerk | 5.0.0-beta.45 |
| @clerk/remix | 4.1.2-snapshot.v3470a88 |
| @clerk/upgrade | 1.0.8-snapshot.v3470a88 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.0.19-snapshot.v3470a88 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.7.1-snapshot.v3470a88 --save-exact
```
`@clerk/elements`
```sh
npm i @clerk/elements@0.8.0-snapshot.v3470a88 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@1.2.2-snapshot.v3470a88 --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@5.0.0-beta.45 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.1.2-snapshot.v3470a88 --save-exact
```
`@clerk/upgrade`
```sh
npm i @clerk/upgrade@1.0.8-snapshot.v3470a88 --save-exact
```

**Pull request merged**
