### PR TITLE
fix(clerk-react): Use derived state over local state in useAuth

### PR DESCRIPTION
**Pull request by jacekradko**
## Description

The `useAuth` hook was capturing Auth context in local state, which could become out of sync with the actual Auth state and causing additional re-renders. Now the `useAuth` hook derives it's state directly from Auth context. 

Thanks @BRKalow for the context and the fix

## Checklist

- [ ] `pnpm test` runs as expected.
- [ ] `pnpm build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Comment by jacekradko** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @jacekradko - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/astro | 1.5.3-snapshot.v20241204220050 |
| @clerk/backend | 1.19.1-snapshot.v20241204220050 |
| @clerk/chrome-extension | 2.0.4-snapshot.v20241204220050 |
| @clerk/clerk-js | 5.38.0-snapshot.v20241204220050 |
| @clerk/elements | 0.20.1-snapshot.v20241204220050 |
| @clerk/clerk-expo | 2.4.0-snapshot.v20241204220050 |
| @clerk/expo-passkeys | 0.0.12-snapshot.v20241204220050 |
| @clerk/express | 1.3.21-snapshot.v20241204220050 |
| @clerk/fastify | 2.0.23-snapshot.v20241204220050 |
| @clerk/localizations | 3.7.3-snapshot.v20241204220050 |
| @clerk/nextjs | 6.7.0-snapshot.v20241204220050 |
| @clerk/nuxt | 0.0.8-snapshot.v20241204220050 |
| @clerk/clerk-react | 5.18.1-snapshot.v20241204220050 |
| @clerk/remix | 4.3.1-snapshot.v20241204220050 |
| @clerk/clerk-sdk-node | 5.0.72-snapshot.v20241204220050 |
| @clerk/shared | 2.18.1-snapshot.v20241204220050 |
| @clerk/tanstack-start | 0.6.1-snapshot.v20241204220050 |
| @clerk/testing | 1.3.33-snapshot.v20241204220050 |
| @clerk/themes | 2.1.51-snapshot.v20241204220050 |
| @clerk/types | 4.37.0-snapshot.v20241204220050 |
| @clerk/ui | 0.1.28-snapshot.v20241204220050 |
| @clerk/vue | 0.0.12-snapshot.v20241204220050 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/astro`
```sh
npm i @clerk/astro@1.5.3-snapshot.v20241204220050 --save-exact
```
`@clerk/backend`
```sh
npm i @clerk/backend@1.19.1-snapshot.v20241204220050 --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@2.0.4-snapshot.v20241204220050 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.38.0-snapshot.v20241204220050 --save-exact
```
`@clerk/elements`
```sh
npm i @clerk/elements@0.20.1-snapshot.v20241204220050 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@2.4.0-snapshot.v20241204220050 --save-exact
```
`@clerk/expo-passkeys`
```sh
npm i @clerk/expo-passkeys@0.0.12-snapshot.v20241204220050 --save-exact
```
`@clerk/express`
```sh
npm i @clerk/express@1.3.21-snapshot.v20241204220050 --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@2.0.23-snapshot.v20241204220050 --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@3.7.3-snapshot.v20241204220050 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@6.7.0-snapshot.v20241204220050 --save-exact
```
`@clerk/nuxt`
```sh
npm i @clerk/nuxt@0.0.8-snapshot.v20241204220050 --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@5.18.1-snapshot.v20241204220050 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.3.1-snapshot.v20241204220050 --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@5.0.72-snapshot.v20241204220050 --save-exact
```
`@clerk/shared`
```sh
npm i @clerk/shared@2.18.1-snapshot.v20241204220050 --save-exact
```
`@clerk/tanstack-start`
```sh
npm i @clerk/tanstack-start@0.6.1-snapshot.v20241204220050 --save-exact
```
`@clerk/testing`
```sh
npm i @clerk/testing@1.3.33-snapshot.v20241204220050 --save-exact
```
`@clerk/themes`
```sh
npm i @clerk/themes@2.1.51-snapshot.v20241204220050 --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@4.37.0-snapshot.v20241204220050 --save-exact
```
`@clerk/ui`
```sh
npm i @clerk/ui@0.1.28-snapshot.v20241204220050 --save-exact
```
`@clerk/vue`
```sh
npm i @clerk/vue@0.0.12-snapshot.v20241204220050 --save-exact
```

**Comment by jacekradko** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @jacekradko - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/astro | 1.5.5-snapshot.v20241206011518 |
| @clerk/backend | 1.20.0-snapshot.v20241206011518 |
| @clerk/chrome-extension | 2.0.6-snapshot.v20241206011518 |
| @clerk/clerk-js | 5.40.0-snapshot.v20241206011518 |
| @clerk/elements | 0.21.1-snapshot.v20241206011518 |
| @clerk/clerk-expo | 2.4.2-snapshot.v20241206011518 |
| @clerk/expo-passkeys | 0.0.14-snapshot.v20241206011518 |
| @clerk/express | 1.3.23-snapshot.v20241206011518 |
| @clerk/fastify | 2.0.25-snapshot.v20241206011518 |
| @clerk/localizations | 3.8.0-snapshot.v20241206011518 |
| @clerk/nextjs | 6.8.0-snapshot.v20241206011518 |
| @clerk/nuxt | 0.0.10-snapshot.v20241206011518 |
| @clerk/clerk-react | 5.19.0-snapshot.v20241206011518 |
| @clerk/remix | 4.3.3-snapshot.v20241206011518 |
| @clerk/clerk-sdk-node | 5.0.74-snapshot.v20241206011518 |
| @clerk/shared | 2.19.1-snapshot.v20241206011518 |
| @clerk/tanstack-start | 0.6.3-snapshot.v20241206011518 |
| @clerk/testing | 1.3.35-snapshot.v20241206011518 |
| @clerk/themes | 2.1.53-snapshot.v20241206011518 |
| @clerk/types | 4.39.0-snapshot.v20241206011518 |
| @clerk/ui | 0.2.1-snapshot.v20241206011518 |
| @clerk/vue | 0.0.14-snapshot.v20241206011518 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/astro`
```sh
npm i @clerk/astro@1.5.5-snapshot.v20241206011518 --save-exact
```
`@clerk/backend`
```sh
npm i @clerk/backend@1.20.0-snapshot.v20241206011518 --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@2.0.6-snapshot.v20241206011518 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.40.0-snapshot.v20241206011518 --save-exact
```
`@clerk/elements`
```sh
npm i @clerk/elements@0.21.1-snapshot.v20241206011518 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@2.4.2-snapshot.v20241206011518 --save-exact
```
`@clerk/expo-passkeys`
```sh
npm i @clerk/expo-passkeys@0.0.14-snapshot.v20241206011518 --save-exact
```
`@clerk/express`
```sh
npm i @clerk/express@1.3.23-snapshot.v20241206011518 --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@2.0.25-snapshot.v20241206011518 --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@3.8.0-snapshot.v20241206011518 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@6.8.0-snapshot.v20241206011518 --save-exact
```
`@clerk/nuxt`
```sh
npm i @clerk/nuxt@0.0.10-snapshot.v20241206011518 --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@5.19.0-snapshot.v20241206011518 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.3.3-snapshot.v20241206011518 --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@5.0.74-snapshot.v20241206011518 --save-exact
```
`@clerk/shared`
```sh
npm i @clerk/shared@2.19.1-snapshot.v20241206011518 --save-exact
```
`@clerk/tanstack-start`
```sh
npm i @clerk/tanstack-start@0.6.3-snapshot.v20241206011518 --save-exact
```
`@clerk/testing`
```sh
npm i @clerk/testing@1.3.35-snapshot.v20241206011518 --save-exact
```
`@clerk/themes`
```sh
npm i @clerk/themes@2.1.53-snapshot.v20241206011518 --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@4.39.0-snapshot.v20241206011518 --save-exact
```
`@clerk/ui`
```sh
npm i @clerk/ui@0.2.1-snapshot.v20241206011518 --save-exact
```
`@clerk/vue`
```sh
npm i @clerk/vue@0.0.14-snapshot.v20241206011518 --save-exact
```

**Review by panteliselef — APPROVED** [review]

**Pull request merged**
