### PR TITLE
feat(clerk-js): Add more alpha scales to make theme changing easier

### PR DESCRIPTION
**Pull request by desiprisg**
## Description

In this PR, we have added some new color scales to the internal theme, for danger/success/warning colors, that are generated in the same way that the `blackAlpha` scale is generated given the `colorAlphaShade` input from `appearance.variables`.
This addition allows us to use a solid color or a color with opacity whenever we need it. A use case for a solid color would be the color of some text, and a use case for an alpha color would be a background color on hover. That color needs to act as an overlay to the background of the element. Example below:

On hover of the button with `backgroundColor: theme.colors.$danger50`:

Screenshot 2024-01-11 at 15 12 43

On hover of the button with `backgroundColor: theme.colors.$dangerAlpha50`:

Screenshot 2024-01-11 at 15 13 35

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/backend`
- [ ] `@clerk/chrome-extension`
- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [ ] `@clerk/localizations`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/remix`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/themes`
- [ ] `@clerk/types`
- [ ] `build/tooling/chore`

### CODE REVIEW

**Comment by octoper** [comment]
!preview

**Comment by desiprisg** [comment]
!preview

**Comment by clerk-cookie** [comment]
Hey @octoper, your preview is currently deploying and should be available shortly.

| Status | Preview | Updated (UTC) |
| :-- | :-- | :-- |
| :cook: _Deploying..._ | [Inspect](https://javascript-preview-mhi6i6r4w.clerkstage.dev) | Jan 11, 2024 12:39 PM |

**Review by nikosdouvlis — APPROVED** [review]
Can we add a screenshot with the before/after (lets use the UserButton component) for future reference?

**Review by anagstef — APPROVED** [review]

**Pull request merged**
