### PR TITLE
[Core 1 backport] Fix script loading and improve bypassing mechanism for Turnstile

### PR DESCRIPTION
**Pull request by anagstef**
## Description

Backports the following PRs to Core 1:
- #4321
- #4322 
- #4325 
- #4327 
- #4329 

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Comment by anagstef** [comment]
!snapshot

**Comment by anagstef** [comment]
!snapshot

**Comment by anagstef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @anagstef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 0.38.14-snapshot.vb996c72 |
| @clerk/chrome-extension | 0.7.9-snapshot.vb996c72 |
| @clerk/clerk-js | 4.73.9-snapshot.vb996c72 |
| @clerk/clerk-expo | 0.20.31-snapshot.vb996c72 |
| @clerk/fastify | 0.6.47-snapshot.vb996c72 |
| gatsby-plugin-clerk | 4.4.50-snapshot.vb996c72 |
| @clerk/localizations | 1.28.9-snapshot.vb996c72 |
| @clerk/nextjs | 4.31.6-snapshot.vb996c72 |
| @clerk/clerk-react | 4.32.4-snapshot.vb996c72 |
| @clerk/remix | 3.2.11-snapshot.vb996c72 |
| @clerk/clerk-sdk-node | 4.13.22-snapshot.vb996c72 |
| @clerk/shared | 1.4.2-snapshot.vb996c72 |
| @clerk/themes | 1.7.19-snapshot.vb996c72 |
| @clerk/types | 3.65.4-snapshot.vb996c72 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/backend`
```sh
npm i @clerk/backend@0.38.14-snapshot.vb996c72 --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@0.7.9-snapshot.vb996c72 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@4.73.9-snapshot.vb996c72 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@0.20.31-snapshot.vb996c72 --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@0.6.47-snapshot.vb996c72 --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@4.4.50-snapshot.vb996c72 --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@1.28.9-snapshot.vb996c72 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@4.31.6-snapshot.vb996c72 --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@4.32.4-snapshot.vb996c72 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@3.2.11-snapshot.vb996c72 --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@4.13.22-snapshot.vb996c72 --save-exact
```
`@clerk/shared`
```sh
npm i @clerk/shared@1.4.2-snapshot.vb996c72 --save-exact
```
`@clerk/themes`
```sh
npm i @clerk/themes@1.7.19-snapshot.vb996c72 --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@3.65.4-snapshot.vb996c72 --save-exact
```

**Review by panteliselef — APPROVED** [review]

**Review by nikosdouvlis — APPROVED** [review]

**Pull request merged**
