### PR TITLE
feat(clerk-js): Introduce interactive captcha

### PR DESCRIPTION
**Pull request by BRKalow**
## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Comment by BRKalow** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @BRKalow - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/chrome-extension | 0.6.20-snapshot.vc141245 |
| @clerk/clerk-js | 4.72.0-snapshot.vc141245 |
| @clerk/clerk-expo | 0.20.15-snapshot.vc141245 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@0.6.20-snapshot.vc141245 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@4.72.0-snapshot.vc141245 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@0.20.15-snapshot.vc141245 --save-exact
```

**Comment by nikosdouvlis** [comment]
Hey @BRKalow :) is this ready for review?

**Comment by BRKalow** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @BRKalow - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/chrome-extension | 0.6.20-snapshot.vbc1085d |
| @clerk/clerk-js | 4.72.0-snapshot.vbc1085d |
| @clerk/clerk-expo | 0.20.15-snapshot.vbc1085d |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@0.6.20-snapshot.vbc1085d --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@4.72.0-snapshot.vbc1085d --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@0.20.15-snapshot.vbc1085d --save-exact
```

**Pull request closed without merging**
