### PR TITLE
fix(astro,backend): Refactor `createRedirect` to support hash routing

### PR DESCRIPTION
**Pull request by panteliselef**
## Description

This PR updates the signature of `createRedirect` and allows for the following
```tsx
createRedirect({
    redirectAdapter,
    baseUrl: clerkRequest.clerkUrl,
    signInUrl: requestState.signInUrl,
    signUpUrl: requestState.signUpUrl,
    publishableKey: getSafeEnv(context).pk!,
}).redirectToSignIn({ returnBackUrl: e.returnBackUrl, asHash: true });
```
`asHash` will construct a correctly formatted url that can be used with hash routing.

### Without `asHash`
```
http://localhost:4011/sign-in?redirect_url=http%3A%2F%2Flocalhost%3A4011%2Fuser
```

### With `asHash:true`
```
http://localhost:4011/sign-in#/?redirect_url=http%3A%2F%2Flocalhost%3A4011%2Fuser
```

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Comment by panteliselef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @panteliselef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/astro | 0.0.2-snapshot.vbc9b8d7 |
| gatsby-plugin-clerk | 5.0.0-beta.45 |
| @clerk/testing | 1.1.10-snapshot.vbc9b8d7 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/astro`
```sh
npm i @clerk/astro@0.0.2-snapshot.vbc9b8d7 --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@5.0.0-beta.45 --save-exact
```
`@clerk/testing`
```sh
npm i @clerk/testing@1.1.10-snapshot.vbc9b8d7 --save-exact
```

**Comment by panteliselef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @panteliselef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/astro | 0.0.2-snapshot.vbbff478 |
| @clerk/backend | 1.3.1-snapshot.vbbff478 |
| @clerk/express | 0.0.16-snapshot.vbbff478 |
| @clerk/fastify | 1.0.18-snapshot.vbbff478 |
| gatsby-plugin-clerk | 5.0.0-beta.45 |
| @clerk/nextjs | 5.2.3-snapshot.vbbff478 |
| @clerk/remix | 4.2.2-snapshot.vbbff478 |
| @clerk/clerk-sdk-node | 5.0.15-snapshot.vbbff478 |
| @clerk/tanstack-start | 0.1.6-snapshot.vbbff478 |
| @clerk/testing | 1.1.10-snapshot.vbbff478 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/astro`
```sh
npm i @clerk/astro@0.0.2-snapshot.vbbff478 --save-exact
```
`@clerk/backend`
```sh
npm i @clerk/backend@1.3.1-snapshot.vbbff478 --save-exact
```
`@clerk/express`
```sh
npm i @clerk/express@0.0.16-snapshot.vbbff478 --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@1.0.18-snapshot.vbbff478 --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@5.0.0-beta.45 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@5.2.3-snapshot.vbbff478 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.2.2-snapshot.vbbff478 --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@5.0.15-snapshot.vbbff478 --save-exact
```
`@clerk/tanstack-start`
```sh
npm i @clerk/tanstack-start@0.1.6-snapshot.vbbff478 --save-exact
```
`@clerk/testing`
```sh
npm i @clerk/testing@1.1.10-snapshot.vbbff478 --save-exact
```

**Comment by panteliselef** [comment]
We will not be needing this for `@clerk/astro` at the moment, as we will have advice devs to use path routing.

**Pull request closed without merging**
