### PR TITLE
Billing snapshot

### PR DESCRIPTION
**Pull request by nikospapcom**
## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Comment by nikospapcom** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @nikospapcom - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| gatsby-plugin-clerk | 5.0.0-beta.45 |

Tip: Use the snippet copy button below to quickly install the required packages.
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@5.0.0-beta.45 --save-exact
```

**Comment by nikospapcom** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @nikospapcom - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 1.1.0-snapshot.vb5b714e |
| @clerk/chrome-extension | 1.0.1-snapshot.vb5b714e |
| @clerk/clerk-js | 5.1.0-snapshot.vb5b714e |
| @clerk/clerk-expo | 1.0.1-snapshot.vb5b714e |
| @clerk/express | 0.0.2-snapshot.vb5b714e |
| @clerk/fastify | 1.0.1-snapshot.vb5b714e |
| gatsby-plugin-clerk | 5.0.0-beta.45 |
| @clerk/localizations | 2.1.0-snapshot.vb5b714e |
| @clerk/nextjs | 5.1.0-snapshot.vb5b714e |
| @clerk/clerk-react | 5.1.0-snapshot.vb5b714e |
| @clerk/remix | 4.0.1-snapshot.vb5b714e |
| @clerk/clerk-sdk-node | 5.0.1-snapshot.vb5b714e |
| @clerk/themes | 2.0.1-snapshot.vb5b714e |
| @clerk/types | 4.1.0-snapshot.vb5b714e |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/backend`
```sh
npm i @clerk/backend@1.1.0-snapshot.vb5b714e --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.0.1-snapshot.vb5b714e --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.1.0-snapshot.vb5b714e --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@1.0.1-snapshot.vb5b714e --save-exact
```
`@clerk/express`
```sh
npm i @clerk/express@0.0.2-snapshot.vb5b714e --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@1.0.1-snapshot.vb5b714e --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@5.0.0-beta.45 --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@2.1.0-snapshot.vb5b714e --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@5.1.0-snapshot.vb5b714e --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@5.1.0-snapshot.vb5b714e --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.0.1-snapshot.vb5b714e --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@5.0.1-snapshot.vb5b714e --save-exact
```
`@clerk/themes`
```sh
npm i @clerk/themes@2.0.1-snapshot.vb5b714e --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@4.1.0-snapshot.vb5b714e --save-exact
```

**Pull request closed without merging**
