### PR TITLE
feat(localizations): Allow the usage of subpath imports

### PR DESCRIPTION
**Pull request by MonsterDeveloper**
## Description

The `localizations` package now allows for [subpath exports](https://nodejs.org/api/packages.html#subpath-exports).

```diff
- import { frFR } from "@clerk/localizations"
+ import { frFR } from "@clerk/localizations/fr-FR"
```

This should help with tree-shaking by helping the bundler to include only specific localization.

This is a non-breaking change-previous imports from `@clerk/localizations` are still working as expected.

## Checklist

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [x] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/backend`
- [ ] `@clerk/chrome-extension`
- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [x] `@clerk/localizations`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/remix`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/themes`
- [ ] `@clerk/types`
- [ ] `build/tooling/chore`

### CODE REVIEW

**Comment by LekoArts** [comment]
Hey Andrew, thanks for the PR!

Seems like a good change, however we'll need to test this a bit more since we have made the experience in the past (with the revamped `@clerk/shared` package) that certain bundlers (like Metro bundler of Expo) have problems with subpath imports. It's annoying but we'd need to check if in that environment it continues to work as expected.

https://github.com/clerk/clerk-expo-starter should be a good starting ground to test. I won't get to testing this today and will be on vacation soon, I'll make sure to hand this PR off to a colleague then.

**Comment by MonsterDeveloper** [comment]
Thanks @LekoArts, looking forward to getting this merged. Let me know if I can help you with the testing.

**Comment by MonsterDeveloper** [comment]
Hey! Any ETA on this one? `localizations` still occupy almost 1 MB (more than a half) of my bundle😔

CleanShot 2023-11-24 at 11 13 19

**Comment by dimkl** [comment]
Hello @MonsterDeveloper 👋 ,
I have created another PR and added a fix for Expo framework. I have added you as co-author since you did the original work. I will close the this one in favor of https://github.com/clerk/javascript/pull/2236

**Comment by MonsterDeveloper** [comment]
Thanks @dimkl ! Looking forward to getting this new PR merged.

**Pull request closed without merging**
