### PR TITLE
fix(clerk-js): Renaming a passkey leaves stale name

### PR DESCRIPTION
**Pull request by panteliselef**
## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Comment by panteliselef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @panteliselef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 1.0.1-snapshot.v754edd5 |
| @clerk/chrome-extension | 1.0.1-snapshot.v754edd5 |
| @clerk/clerk-js | 5.0.1-snapshot.v754edd5 |
| @clerk/clerk-expo | 1.0.1-snapshot.v754edd5 |
| @clerk/fastify | 1.0.1-snapshot.v754edd5 |
| gatsby-plugin-clerk | 5.0.1-snapshot.v754edd5 |
| @clerk/localizations | 2.0.1-snapshot.v754edd5 |
| @clerk/nextjs | 5.0.1-snapshot.v754edd5 |
| @clerk/clerk-react | 5.0.1-snapshot.v754edd5 |
| @clerk/remix | 4.0.1-snapshot.v754edd5 |
| @clerk/clerk-sdk-node | 5.0.1-snapshot.v754edd5 |
| @clerk/shared | 2.0.1-snapshot.v754edd5 |
| @clerk/themes | 2.0.1-snapshot.v754edd5 |
| @clerk/types | 4.0.1-snapshot.v754edd5 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/backend`
```sh
npm i @clerk/backend@1.0.1-snapshot.v754edd5 --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.0.1-snapshot.v754edd5 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.0.1-snapshot.v754edd5 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@1.0.1-snapshot.v754edd5 --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@1.0.1-snapshot.v754edd5 --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@5.0.1-snapshot.v754edd5 --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@2.0.1-snapshot.v754edd5 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@5.0.1-snapshot.v754edd5 --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@5.0.1-snapshot.v754edd5 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.0.1-snapshot.v754edd5 --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@5.0.1-snapshot.v754edd5 --save-exact
```
`@clerk/shared`
```sh
npm i @clerk/shared@2.0.1-snapshot.v754edd5 --save-exact
```
`@clerk/themes`
```sh
npm i @clerk/themes@2.0.1-snapshot.v754edd5 --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@4.0.1-snapshot.v754edd5 --save-exact
```

**Comment by panteliselef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @panteliselef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 1.0.1-snapshot.v3eb7a55 |
| @clerk/chrome-extension | 1.0.1-snapshot.v3eb7a55 |
| @clerk/clerk-js | 5.0.1-snapshot.v3eb7a55 |
| @clerk/clerk-expo | 1.0.1-snapshot.v3eb7a55 |
| @clerk/fastify | 1.0.1-snapshot.v3eb7a55 |
| gatsby-plugin-clerk | 5.0.1-snapshot.v3eb7a55 |
| @clerk/localizations | 2.0.1-snapshot.v3eb7a55 |
| @clerk/nextjs | 5.0.1-snapshot.v3eb7a55 |
| @clerk/clerk-react | 5.0.1-snapshot.v3eb7a55 |
| @clerk/remix | 4.0.1-snapshot.v3eb7a55 |
| @clerk/clerk-sdk-node | 5.0.1-snapshot.v3eb7a55 |
| @clerk/shared | 2.0.1-snapshot.v3eb7a55 |
| @clerk/themes | 2.0.1-snapshot.v3eb7a55 |
| @clerk/types | 4.0.1-snapshot.v3eb7a55 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/backend`
```sh
npm i @clerk/backend@1.0.1-snapshot.v3eb7a55 --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.0.1-snapshot.v3eb7a55 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.0.1-snapshot.v3eb7a55 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@1.0.1-snapshot.v3eb7a55 --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@1.0.1-snapshot.v3eb7a55 --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@5.0.1-snapshot.v3eb7a55 --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@2.0.1-snapshot.v3eb7a55 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@5.0.1-snapshot.v3eb7a55 --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@5.0.1-snapshot.v3eb7a55 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.0.1-snapshot.v3eb7a55 --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@5.0.1-snapshot.v3eb7a55 --save-exact
```
`@clerk/shared`
```sh
npm i @clerk/shared@2.0.1-snapshot.v3eb7a55 --save-exact
```
`@clerk/themes`
```sh
npm i @clerk/themes@2.0.1-snapshot.v3eb7a55 --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@4.0.1-snapshot.v3eb7a55 --save-exact
```

**Comment by BRKalow** [comment]
@panteliselef why does changing the key (remounting) fix it? Is there some underlying query cache that's not being purged correctly?

**Comment by panteliselef** [comment]
@BRKalow I created this just for snapshot version. Personally I couldn't reproduce nor any other app that I have only seems to have this issue.

@mzhong9723 seems to be the only one who has managed to hit this, I've not identified the core issue yet.

This information comes right back to us due to client piggybacking, and no cache is used.

**Pull request closed without merging**
