### PR TITLE
feat(nextjs,shared,backend,clerk-react): Support permissions in Gate

### PR DESCRIPTION
**Pull request by panteliselef**
## Description
Ingore, i just need a snapshot for v4

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/backend`
- [ ] `@clerk/chrome-extension`
- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [ ] `@clerk/localizations`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/remix`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/themes`
- [ ] `@clerk/types`
- [ ] `build/tooling/chore`

### CODE REVIEW

**Comment by panteliselef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @panteliselef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/chrome-extension | 0.5.2-snapshot.va4f4ad4 |
| @clerk/clerk-js | 4.65.2-snapshot.va4f4ad4 |
| @clerk/clerk-expo | 0.19.18-snapshot.va4f4ad4 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@0.5.2-snapshot.va4f4ad4 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@4.65.2-snapshot.va4f4ad4 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@0.19.18-snapshot.va4f4ad4 --save-exact
```

**Comment by panteliselef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @panteliselef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 0.35.0-snapshot.v75e2d80 |
| @clerk/chrome-extension | 0.5.2-snapshot.v75e2d80 |
| @clerk/clerk-js | 4.65.2-snapshot.v75e2d80 |
| @clerk/clerk-expo | 0.19.18-snapshot.v75e2d80 |
| @clerk/fastify | 0.6.23-snapshot.v75e2d80 |
| gatsby-plugin-clerk | 4.4.24-snapshot.v75e2d80 |
| @clerk/localizations | 1.26.10-snapshot.v75e2d80 |
| @clerk/nextjs | 4.28.0-snapshot.v75e2d80 |
| @clerk/clerk-react | 4.29.0-snapshot.v75e2d80 |
| @clerk/remix | 3.1.6-snapshot.v75e2d80 |
| @clerk/clerk-sdk-node | 4.12.22-snapshot.v75e2d80 |
| @clerk/shared | 1.2.0-snapshot.v75e2d80 |
| @clerk/types | 3.59.0-snapshot.v75e2d80 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/backend`
```sh
npm i @clerk/backend@0.35.0-snapshot.v75e2d80 --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@0.5.2-snapshot.v75e2d80 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@4.65.2-snapshot.v75e2d80 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@0.19.18-snapshot.v75e2d80 --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@0.6.23-snapshot.v75e2d80 --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@4.4.24-snapshot.v75e2d80 --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@1.26.10-snapshot.v75e2d80 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@4.28.0-snapshot.v75e2d80 --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@4.29.0-snapshot.v75e2d80 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@3.1.6-snapshot.v75e2d80 --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@4.12.22-snapshot.v75e2d80 --save-exact
```
`@clerk/shared`
```sh
npm i @clerk/shared@1.2.0-snapshot.v75e2d80 --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@3.59.0-snapshot.v75e2d80 --save-exact
```

**Pull request closed without merging**
