### PR TITLE
feat(*): Set PACKAGE_NAME and PACKAGE_VERSION as the user-agent header in BAPI requests

### PR DESCRIPTION
**Pull request by nikosdouvlis**
## Description

Changes:

- Update @clerk/backend test builds to use tsup to supporting testing with build-time constants
- Replace Clerk-Backend-SDK header with User-Agent for all server Clerk packages
- Add Clerk package version for each SDK in User-Agent header

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/backend`
- [ ] `@clerk/chrome-extension`
- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [ ] `@clerk/localizations`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/remix`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/themes`
- [ ] `@clerk/types`
- [ ] `build/tooling/chore`

### CODE REVIEW

**Comment by nikosdouvlis** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @nikosdouvlis - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 0.38.0-snapshot.v944b9de |
| @clerk/fastify | 0.7.0-snapshot.v944b9de |
| gatsby-plugin-clerk | 4.5.0-snapshot.v944b9de |
| @clerk/nextjs | 4.30.0-snapshot.v944b9de |
| @clerk/remix | 3.2.0-snapshot.v944b9de |
| @clerk/clerk-sdk-node | 4.14.0-snapshot.v944b9de |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/backend`
```sh
npm i @clerk/backend@0.38.0-snapshot.v944b9de --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@0.7.0-snapshot.v944b9de --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@4.5.0-snapshot.v944b9de --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@4.30.0-snapshot.v944b9de --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@3.2.0-snapshot.v944b9de --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@4.14.0-snapshot.v944b9de --save-exact
```

**Review by dimkl — APPROVED** [review]

**Review by anagstef — APPROVED** [review]

**Comment by nikosdouvlis** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @nikosdouvlis - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 0.37.2-snapshot.v790818f |
| @clerk/fastify | 0.6.31-snapshot.v790818f |
| gatsby-plugin-clerk | 4.4.33-snapshot.v790818f |
| @clerk/nextjs | 4.29.3-snapshot.v790818f |
| @clerk/remix | 3.1.15-snapshot.v790818f |
| @clerk/clerk-sdk-node | 4.13.6-snapshot.v790818f |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/backend`
```sh
npm i @clerk/backend@0.37.2-snapshot.v790818f --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@0.6.31-snapshot.v790818f --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@4.4.33-snapshot.v790818f --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@4.29.3-snapshot.v790818f --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@3.1.15-snapshot.v790818f --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@4.13.6-snapshot.v790818f --save-exact
```

**Pull request merged**
