### PR TITLE
fix(testing): Use .mjs for esm exports

### PR DESCRIPTION
**Pull request by gcascio**
## Description

ESM imports from the testing package currently fail with e.g.

`SyntaxError: The requested module '@clerk/testing/playwright' does not provide an export named 'clerkSetup'`

A reproduction can be found [here](https://github.com/gcascio/playwright-clerk-nextjs-example) which is a clone of the official [clerk](https://github.com/clerk/playwright-clerk-nextjs-example) example changed to `type: "module"`.

This PR removes the `legacyOutput` flag from the tsup config and instead exports ESM modules with the `.mjs` extension.

## Checklist

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [x] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Comment by anagstef** [comment]
Thank you for your contribution and detailed PR description. 🙏

**Comment by anagstef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @anagstef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 1.1.0-snapshot.v4c5edbc |
| @clerk/chrome-extension | 1.0.2-snapshot.v4c5edbc |
| @clerk/clerk-js | 5.1.1-snapshot.v4c5edbc |
| @clerk/clerk-expo | 1.0.2-snapshot.v4c5edbc |
| @clerk/express | 0.0.3-snapshot.v4c5edbc |
| @clerk/fastify | 1.0.2-snapshot.v4c5edbc |
| gatsby-plugin-clerk | 5.0.0-beta.45 |
| @clerk/nextjs | 5.0.3-snapshot.v4c5edbc |
| @clerk/remix | 4.0.2-snapshot.v4c5edbc |
| @clerk/clerk-sdk-node | 5.0.2-snapshot.v4c5edbc |
| @clerk/testing | 1.0.1-snapshot.v4c5edbc |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/backend`
```sh
npm i @clerk/backend@1.1.0-snapshot.v4c5edbc --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.0.2-snapshot.v4c5edbc --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.1.1-snapshot.v4c5edbc --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@1.0.2-snapshot.v4c5edbc --save-exact
```
`@clerk/express`
```sh
npm i @clerk/express@0.0.3-snapshot.v4c5edbc --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@1.0.2-snapshot.v4c5edbc --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@5.0.0-beta.45 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@5.0.3-snapshot.v4c5edbc --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.0.2-snapshot.v4c5edbc --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@5.0.2-snapshot.v4c5edbc --save-exact
```
`@clerk/testing`
```sh
npm i @clerk/testing@1.0.1-snapshot.v4c5edbc --save-exact
```

**Review by anagstef — APPROVED** [review]
Great job! 💯 Thank you! 🙏

**Pull request merged**
