### PR TITLE
fix(clerk-js): Set localhost SameSite=None cookies as Secure

### PR DESCRIPTION
**Pull request by anagstef**
## Description

This PR removes the specific fix we did a while ago for Cypress.
The real reason our cookies where getting deleted in Cypress Chrome is because Chrome requires `Secure` when setting `SameSite=None` cookies.

Safari needs a bit of a different handling because it does not consider `localhost` to be a secure context, so in Safari localhost cookies cannot have the `Secure` attribute.

###  So the new logic about the `Secure` attribute on cookies goes as follows:
- If you are in a `https` location then add `Secure` on cookies.
- If you are not in `https`:
  - If the browser is Safari, then do not add `Secure` (safari considers secure only `https` origins).
  - If the `window.isSecureContext` property exists, then respect it (safari does not work correctly with this, that's why we added a condition before this)
  - Lastly, if the window location is `localhost` and SameSite is set to `None`, add the `Secure` attribute (that's required by Chrome)

## Checklist

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [x] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Comment by anagstef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @anagstef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/chrome-extension | 1.1.0-snapshot.v1f5b5e4 |
| @clerk/clerk-js | 5.7.2-snapshot.v1f5b5e4 |
| @clerk/elements | 0.9.0-snapshot.v1f5b5e4 |
| @clerk/clerk-expo | 1.2.3-snapshot.v1f5b5e4 |
| gatsby-plugin-clerk | 5.0.0-beta.45 |
| @clerk/localizations | 2.4.6-snapshot.v1f5b5e4 |
| @clerk/ui | 0.1.3-snapshot.v1f5b5e4 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.1.0-snapshot.v1f5b5e4 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.7.2-snapshot.v1f5b5e4 --save-exact
```
`@clerk/elements`
```sh
npm i @clerk/elements@0.9.0-snapshot.v1f5b5e4 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@1.2.3-snapshot.v1f5b5e4 --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@5.0.0-beta.45 --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@2.4.6-snapshot.v1f5b5e4 --save-exact
```
`@clerk/ui`
```sh
npm i @clerk/ui@0.1.3-snapshot.v1f5b5e4 --save-exact
```

**Comment by panteliselef** [comment]
So it seems this PR reverts #3245 and proposes another solution

**Comment by anagstef** [comment]
@panteliselef Exactly! This PR removes the hacky Cypress fix and proposes a more holistic solution for `Secure` when on `localhost` which also fixes the Cypress issues, even if the cookies set are `SameSite=None`.

**Review by BRKalow — APPROVED** [review]

**Review by panteliselef — APPROVED** [review]

**Pull request merged**
