### PR TITLE
chore(repo): Remove eslint-config-custom from react's deps

### PR DESCRIPTION
**Pull request by BRKalow**
## Description

`eslint-config-custom` should only be a `devDependency`, not a direct dependency. This ensures we don't attempt to download the package when `@clerk/clerk-react` is installed.

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Review by tmilewski — APPROVED** [review]

**Comment by blaine-arcjet** [comment]
I think this exists as a dependency in other package.json files in the monorepo.

**Comment by blaine-arcjet** [comment]
Also, why doesn't this use a scoped package so there is no risk at all of downloading the published package?

**Comment by BRKalow** [comment]
@blaine-arcjet This was the only entry under `dependencies` that I could find 🤔. `devDependencies` should be a non-issue. Yeah, agreed on the package name. Will update, thanks!

**Review by nikosdouvlis — APPROVED** [review]

**Review by desiprisg — APPROVED** [review]

**Comment by blaine-arcjet** [comment]
Are y'all planning to roll this out? It's a supply chain vulnerability in your packages

**Review by LekoArts — APPROVED** [review]

**Pull request merged**
