### PR TITLE
fix(clerk-js): Move Invite button above the table in every tab for members page in OP

### PR DESCRIPTION
**Pull request by octoper**
## Before:
CleanShot 2024-02-15 at 15 17 51@2x

## After:
CleanShot 2024-02-15 at 15 17 19@2x

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Comment by octoper** [comment]
!preview

**Comment by clerk-cookie** [comment]
Hey @octoper, your preview is currently deploying and should be available shortly.

| Status | Preview | Updated (UTC) |
| :-- | :-- | :-- |
| :cook: _Deploying..._ | [Inspect](https://javascript-preview-protyw60o.clerkstage.dev) | Feb 15, 2024 01:26 PM |

**Comment by anagstef** [comment]
!preview

**Comment by octoper** [comment]
!preview

**Comment by anagstef** [comment]
!preview

**Review by anagstef — APPROVED** [review]

**Pull request merged**
