### PR TITLE
fix(clerk-js): Fix clipped phone number picker in SignIn/SignUp

### PR DESCRIPTION
**Pull request by octoper**
## Description

This PR prevents phone number picker getting clipped in `<SignIn/>` / `<SignUp/>` components

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Comment by octoper** [comment]
!preview

**Comment by clerk-cookie** [comment]
Hey @octoper, your preview is currently deploying and should be available shortly.

| Status | Preview | Updated (UTC) |
| :-- | :-- | :-- |
| :cook: _Deploying..._ | [Inspect](https://javascript-preview-21hvsj6qr.clerkstage.dev) | Feb 12, 2024 05:38 PM |

**Comment by octoper** [comment]
!preview

**Review by anagstef — APPROVED** [review]
💯

**Pull request merged**
