### PR TITLE
feat(clerk-js): Introduce experimental support for Google One Tap (#3176)

### PR DESCRIPTION
**Pull request by panteliselef**
## Description
This PR backports #3176 in v4

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Comment by panteliselef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @panteliselef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 0.38.7-snapshot.va479472 |
| @clerk/chrome-extension | 0.6.22-snapshot.va479472 |
| @clerk/clerk-js | 4.72.0-snapshot.va479472 |
| @clerk/clerk-expo | 0.20.17-snapshot.va479472 |
| @clerk/fastify | 0.6.40-snapshot.va479472 |
| gatsby-plugin-clerk | 4.4.42-snapshot.va479472 |
| @clerk/localizations | 1.28.3-snapshot.va479472 |
| @clerk/nextjs | 4.30.0-snapshot.va479472 |
| @clerk/clerk-react | 4.31.0-snapshot.va479472 |
| @clerk/remix | 3.2.4-snapshot.va479472 |
| @clerk/clerk-sdk-node | 4.13.15-snapshot.va479472 |
| @clerk/themes | 1.7.13-snapshot.va479472 |
| @clerk/types | 3.64.0-snapshot.va479472 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/backend`
```sh
npm i @clerk/backend@0.38.7-snapshot.va479472 --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@0.6.22-snapshot.va479472 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@4.72.0-snapshot.va479472 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@0.20.17-snapshot.va479472 --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@0.6.40-snapshot.va479472 --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@4.4.42-snapshot.va479472 --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@1.28.3-snapshot.va479472 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@4.30.0-snapshot.va479472 --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@4.31.0-snapshot.va479472 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@3.2.4-snapshot.va479472 --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@4.13.15-snapshot.va479472 --save-exact
```
`@clerk/themes`
```sh
npm i @clerk/themes@1.7.13-snapshot.va479472 --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@3.64.0-snapshot.va479472 --save-exact
```

**Comment by BRKalow** [comment]
@panteliselef do we need to include this as well? https://github.com/clerk/javascript/pull/3198

**Review by BRKalow — APPROVED** [review]

**Comment by panteliselef** [comment]
Yes i will include before merging this one

**Comment by panteliselef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @panteliselef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 0.38.7-snapshot.v046a94c |
| @clerk/chrome-extension | 0.6.22-snapshot.v046a94c |
| @clerk/clerk-js | 4.72.0-snapshot.v046a94c |
| @clerk/clerk-expo | 0.20.17-snapshot.v046a94c |
| @clerk/fastify | 0.6.40-snapshot.v046a94c |
| gatsby-plugin-clerk | 4.4.42-snapshot.v046a94c |
| @clerk/localizations | 1.28.3-snapshot.v046a94c |
| @clerk/nextjs | 4.30.0-snapshot.v046a94c |
| @clerk/clerk-react | 4.31.0-snapshot.v046a94c |
| @clerk/remix | 3.2.4-snapshot.v046a94c |
| @clerk/clerk-sdk-node | 4.13.15-snapshot.v046a94c |
| @clerk/themes | 1.7.13-snapshot.v046a94c |
| @clerk/types | 3.64.0-snapshot.v046a94c |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/backend`
```sh
npm i @clerk/backend@0.38.7-snapshot.v046a94c --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@0.6.22-snapshot.v046a94c --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@4.72.0-snapshot.v046a94c --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@0.20.17-snapshot.v046a94c --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@0.6.40-snapshot.v046a94c --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@4.4.42-snapshot.v046a94c --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@1.28.3-snapshot.v046a94c --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@4.30.0-snapshot.v046a94c --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@4.31.0-snapshot.v046a94c --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@3.2.4-snapshot.v046a94c --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@4.13.15-snapshot.v046a94c --save-exact
```
`@clerk/themes`
```sh
npm i @clerk/themes@1.7.13-snapshot.v046a94c --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@3.64.0-snapshot.v046a94c --save-exact
```

**Pull request merged**
