### PR TITLE
[WIP] chore(nextjs): Accountless based on cookies

### PR DESCRIPTION
**Pull request by panteliselef**
## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Comment by panteliselef** [comment]
!snapshot

**Comment by panteliselef** [comment]
!snapshot

**Comment by panteliselef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @panteliselef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/astro | 1.4.8-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 |
| @clerk/backend | 1.16.0-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 |
| @clerk/chrome-extension | 1.3.31-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 |
| @clerk/clerk-js | 5.32.0-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 |
| @clerk/elements | 0.18.6-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 |
| @clerk/clerk-expo | 2.3.0-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 |
| @clerk/expo-passkeys | 0.0.2-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 |
| @clerk/express | 1.3.10-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 |
| @clerk/fastify | 2.0.12-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 |
| @clerk/localizations | 3.5.1-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 |
| @clerk/nextjs | 6.3.0-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 |
| @clerk/clerk-react | 5.15.2-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 |
| @clerk/remix | 4.2.48-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 |
| @clerk/clerk-sdk-node | 5.0.61-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 |
| @clerk/shared | 2.12.0-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 |
| @clerk/tanstack-start | 0.4.24-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 |
| @clerk/testing | 1.3.22-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 |
| @clerk/themes | 2.1.42-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 |
| @clerk/types | 4.31.0-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 |
| @clerk/ui | 0.1.17-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/astro`
```sh
npm i @clerk/astro@1.4.8-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 --save-exact
```
`@clerk/backend`
```sh
npm i @clerk/backend@1.16.0-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.3.31-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.32.0-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 --save-exact
```
`@clerk/elements`
```sh
npm i @clerk/elements@0.18.6-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@2.3.0-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 --save-exact
```
`@clerk/expo-passkeys`
```sh
npm i @clerk/expo-passkeys@0.0.2-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 --save-exact
```
`@clerk/express`
```sh
npm i @clerk/express@1.3.10-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@2.0.12-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@3.5.1-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@6.3.0-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@5.15.2-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.2.48-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@5.0.61-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 --save-exact
```
`@clerk/shared`
```sh
npm i @clerk/shared@2.12.0-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 --save-exact
```
`@clerk/tanstack-start`
```sh
npm i @clerk/tanstack-start@0.4.24-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 --save-exact
```
`@clerk/testing`
```sh
npm i @clerk/testing@1.3.22-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 --save-exact
```
`@clerk/themes`
```sh
npm i @clerk/themes@2.1.42-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@4.31.0-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 --save-exact
```
`@clerk/ui`
```sh
npm i @clerk/ui@0.1.17-snapshot.v9e8a9099dfa5685b375b3c2206d03dd14a27aec8 --save-exact
```

**Comment by panteliselef** [comment]
Closing as we are exploring alternative approaches

**Pull request closed without merging**
