### PR TITLE
fix(backend): Fix `getToken` returning `null` when resolving the handshake payload

### PR DESCRIPTION
**Pull request by anagstef**
## Description

This PR fixes an issue on Remix where `getToken()` returns no token when redirecting back when sign-in and handshake are triggered.

The issue exists because the `getToken()` is getting the session token from the request cookie, but when returning from an external sign-in page (e.g. OAuth or Account Portal) on the request there is still the `__clerk_handshake` cookie, because it's not yet resolved. The issue exists only on production, and also does not happen to nextjs, because middleware has already resolved the handshake.

With this PR we pass the session token that exists inside the handshake payload to be returned when calling `getToken()`.

## Checklist

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [x] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Comment by anagstef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @anagstef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/astro | 1.0.1-snapshot.v7ada807 |
| @clerk/backend | 1.4.0-snapshot.v7ada807 |
| @clerk/chrome-extension | 1.1.5-snapshot.v7ada807 |
| @clerk/clerk-js | 5.10.0-snapshot.v7ada807 |
| @clerk/elements | 0.10.5-snapshot.v7ada807 |
| @clerk/clerk-expo | 1.2.8-snapshot.v7ada807 |
| @clerk/express | 0.0.18-snapshot.v7ada807 |
| @clerk/fastify | 1.0.20-snapshot.v7ada807 |
| gatsby-plugin-clerk | 5.0.0-beta.45 |
| @clerk/nextjs | 5.2.5-snapshot.v7ada807 |
| @clerk/clerk-react | 5.2.9-snapshot.v7ada807 |
| @clerk/remix | 4.2.4-snapshot.v7ada807 |
| @clerk/clerk-sdk-node | 5.0.17-snapshot.v7ada807 |
| @clerk/shared | 2.4.0-snapshot.v7ada807 |
| @clerk/tanstack-start | 0.1.8-snapshot.v7ada807 |
| @clerk/testing | 1.1.12-snapshot.v7ada807 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/astro`
```sh
npm i @clerk/astro@1.0.1-snapshot.v7ada807 --save-exact
```
`@clerk/backend`
```sh
npm i @clerk/backend@1.4.0-snapshot.v7ada807 --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.1.5-snapshot.v7ada807 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.10.0-snapshot.v7ada807 --save-exact
```
`@clerk/elements`
```sh
npm i @clerk/elements@0.10.5-snapshot.v7ada807 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@1.2.8-snapshot.v7ada807 --save-exact
```
`@clerk/express`
```sh
npm i @clerk/express@0.0.18-snapshot.v7ada807 --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@1.0.20-snapshot.v7ada807 --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@5.0.0-beta.45 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@5.2.5-snapshot.v7ada807 --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@5.2.9-snapshot.v7ada807 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.2.4-snapshot.v7ada807 --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@5.0.17-snapshot.v7ada807 --save-exact
```
`@clerk/shared`
```sh
npm i @clerk/shared@2.4.0-snapshot.v7ada807 --save-exact
```
`@clerk/tanstack-start`
```sh
npm i @clerk/tanstack-start@0.1.8-snapshot.v7ada807 --save-exact
```
`@clerk/testing`
```sh
npm i @clerk/testing@1.1.12-snapshot.v7ada807 --save-exact
```

**Comment by anagstef** [comment]
!snapshot

**Review by BRKalow — APPROVED** [review]
👏

**Comment by anagstef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @anagstef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/astro | 1.0.2-snapshot.vcbde650 |
| @clerk/backend | 1.4.1-snapshot.vcbde650 |
| @clerk/chrome-extension | 1.1.6-snapshot.vcbde650 |
| @clerk/clerk-js | 5.10.1-snapshot.vcbde650 |
| @clerk/clerk-expo | 1.2.9-snapshot.vcbde650 |
| @clerk/express | 0.0.19-snapshot.vcbde650 |
| @clerk/fastify | 1.0.21-snapshot.vcbde650 |
| gatsby-plugin-clerk | 5.0.0-beta.45 |
| @clerk/localizations | 2.5.1-snapshot.vcbde650 |
| @clerk/nextjs | 5.2.6-snapshot.vcbde650 |
| @clerk/remix | 4.2.5-snapshot.vcbde650 |
| @clerk/clerk-sdk-node | 5.0.18-snapshot.vcbde650 |
| @clerk/tanstack-start | 0.1.9-snapshot.vcbde650 |
| @clerk/testing | 1.2.1-snapshot.vcbde650 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/astro`
```sh
npm i @clerk/astro@1.0.2-snapshot.vcbde650 --save-exact
```
`@clerk/backend`
```sh
npm i @clerk/backend@1.4.1-snapshot.vcbde650 --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.1.6-snapshot.vcbde650 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.10.1-snapshot.vcbde650 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@1.2.9-snapshot.vcbde650 --save-exact
```
`@clerk/express`
```sh
npm i @clerk/express@0.0.19-snapshot.vcbde650 --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@1.0.21-snapshot.vcbde650 --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@5.0.0-beta.45 --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@2.5.1-snapshot.vcbde650 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@5.2.6-snapshot.vcbde650 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.2.5-snapshot.vcbde650 --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@5.0.18-snapshot.vcbde650 --save-exact
```
`@clerk/tanstack-start`
```sh
npm i @clerk/tanstack-start@0.1.9-snapshot.vcbde650 --save-exact
```
`@clerk/testing`
```sh
npm i @clerk/testing@1.2.1-snapshot.vcbde650 --save-exact
```

**Review by nikosdouvlis — APPROVED** [review]
This makes sense to me 👍🏻

**Review by dimkl — APPROVED** [review]

**Pull request merged**
