### PR TITLE
fix(nextjs): Remove sourcemaps from bundled server-actions

### PR DESCRIPTION
**Pull request by nikosdouvlis**
## Description

This PR excludes all server actions imported by client components. Even though we correctly build and bundle the Nextjs package (compiled files + sourcemaps), it seems that the sourcemaps for any server actions imported by client components are not served by nextjs when running `npm run dev` or `npm run start`.

This PR solves the `Error: Clerk: auth() was called but Clerk can't detect usage of authMiddleware().` error many users where getting during init. The error only popped up when browser devtools were open, as the browser would eventually request the sourcemap for the server action.

The URL of the request is similar to `/_next/...../filename.map.js` which our default matcher ignores, so the middleware wouldn't run. The Clerk error would then be thrown if any Clerk helpers were used in a layout as the 404 page still renders that layout.

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Comment by nikosdouvlis** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @nikosdouvlis - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/astro | 1.0.1-snapshot.v8ec6e1b |
| @clerk/backend | 1.4.0-snapshot.v8ec6e1b |
| @clerk/chrome-extension | 1.1.5-snapshot.v8ec6e1b |
| @clerk/clerk-js | 5.10.0-snapshot.v8ec6e1b |
| @clerk/elements | 0.10.5-snapshot.v8ec6e1b |
| @clerk/clerk-expo | 1.2.8-snapshot.v8ec6e1b |
| @clerk/express | 0.0.18-snapshot.v8ec6e1b |
| @clerk/fastify | 1.0.20-snapshot.v8ec6e1b |
| gatsby-plugin-clerk | 5.0.0-beta.45 |
| @clerk/localizations | 2.5.0-snapshot.v8ec6e1b |
| @clerk/nextjs | 5.2.5-snapshot.v8ec6e1b |
| @clerk/clerk-react | 5.2.9-snapshot.v8ec6e1b |
| @clerk/remix | 4.2.4-snapshot.v8ec6e1b |
| @clerk/clerk-sdk-node | 5.0.17-snapshot.v8ec6e1b |
| @clerk/shared | 2.4.0-snapshot.v8ec6e1b |
| @clerk/tanstack-start | 0.1.8-snapshot.v8ec6e1b |
| @clerk/testing | 1.2.0-snapshot.v8ec6e1b |
| @clerk/themes | 2.1.13-snapshot.v8ec6e1b |
| @clerk/types | 4.9.0-snapshot.v8ec6e1b |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/astro`
```sh
npm i @clerk/astro@1.0.1-snapshot.v8ec6e1b --save-exact
```
`@clerk/backend`
```sh
npm i @clerk/backend@1.4.0-snapshot.v8ec6e1b --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.1.5-snapshot.v8ec6e1b --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.10.0-snapshot.v8ec6e1b --save-exact
```
`@clerk/elements`
```sh
npm i @clerk/elements@0.10.5-snapshot.v8ec6e1b --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@1.2.8-snapshot.v8ec6e1b --save-exact
```
`@clerk/express`
```sh
npm i @clerk/express@0.0.18-snapshot.v8ec6e1b --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@1.0.20-snapshot.v8ec6e1b --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@5.0.0-beta.45 --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@2.5.0-snapshot.v8ec6e1b --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@5.2.5-snapshot.v8ec6e1b --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@5.2.9-snapshot.v8ec6e1b --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.2.4-snapshot.v8ec6e1b --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@5.0.17-snapshot.v8ec6e1b --save-exact
```
`@clerk/shared`
```sh
npm i @clerk/shared@2.4.0-snapshot.v8ec6e1b --save-exact
```
`@clerk/tanstack-start`
```sh
npm i @clerk/tanstack-start@0.1.8-snapshot.v8ec6e1b --save-exact
```
`@clerk/testing`
```sh
npm i @clerk/testing@1.2.0-snapshot.v8ec6e1b --save-exact
```
`@clerk/themes`
```sh
npm i @clerk/themes@2.1.13-snapshot.v8ec6e1b --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@4.9.0-snapshot.v8ec6e1b --save-exact
```

**Comment by nikosdouvlis** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @nikosdouvlis - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/astro | 1.0.1-snapshot.v910e99d |
| @clerk/backend | 1.4.0-snapshot.v910e99d |
| @clerk/chrome-extension | 1.1.5-snapshot.v910e99d |
| @clerk/clerk-js | 5.10.0-snapshot.v910e99d |
| @clerk/elements | 0.10.5-snapshot.v910e99d |
| @clerk/clerk-expo | 1.2.8-snapshot.v910e99d |
| @clerk/express | 0.0.18-snapshot.v910e99d |
| @clerk/fastify | 1.0.20-snapshot.v910e99d |
| gatsby-plugin-clerk | 5.0.0-beta.45 |
| @clerk/localizations | 2.5.0-snapshot.v910e99d |
| @clerk/nextjs | 5.2.5-snapshot.v910e99d |
| @clerk/clerk-react | 5.2.9-snapshot.v910e99d |
| @clerk/remix | 4.2.4-snapshot.v910e99d |
| @clerk/clerk-sdk-node | 5.0.17-snapshot.v910e99d |
| @clerk/shared | 2.4.0-snapshot.v910e99d |
| @clerk/tanstack-start | 0.1.8-snapshot.v910e99d |
| @clerk/testing | 1.2.0-snapshot.v910e99d |
| @clerk/themes | 2.1.13-snapshot.v910e99d |
| @clerk/types | 4.9.0-snapshot.v910e99d |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/astro`
```sh
npm i @clerk/astro@1.0.1-snapshot.v910e99d --save-exact
```
`@clerk/backend`
```sh
npm i @clerk/backend@1.4.0-snapshot.v910e99d --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.1.5-snapshot.v910e99d --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.10.0-snapshot.v910e99d --save-exact
```
`@clerk/elements`
```sh
npm i @clerk/elements@0.10.5-snapshot.v910e99d --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@1.2.8-snapshot.v910e99d --save-exact
```
`@clerk/express`
```sh
npm i @clerk/express@0.0.18-snapshot.v910e99d --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@1.0.20-snapshot.v910e99d --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@5.0.0-beta.45 --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@2.5.0-snapshot.v910e99d --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@5.2.5-snapshot.v910e99d --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@5.2.9-snapshot.v910e99d --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.2.4-snapshot.v910e99d --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@5.0.17-snapshot.v910e99d --save-exact
```
`@clerk/shared`
```sh
npm i @clerk/shared@2.4.0-snapshot.v910e99d --save-exact
```
`@clerk/tanstack-start`
```sh
npm i @clerk/tanstack-start@0.1.8-snapshot.v910e99d --save-exact
```
`@clerk/testing`
```sh
npm i @clerk/testing@1.2.0-snapshot.v910e99d --save-exact
```
`@clerk/themes`
```sh
npm i @clerk/themes@2.1.13-snapshot.v910e99d --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@4.9.0-snapshot.v910e99d --save-exact
```

**Review by panteliselef — APPROVED** [review]
Nice catch, was this happening for a while, or after a specific nextjs version ?

**Comment by nikosdouvlis** [comment]
> Nice catch, was this happening for a while, or after a specific nextjs version ?

I'm not sure when/if sourcemap handling changed at some point by Nextjs, but we introduced the `invalidateCache` server action in `@clerk/nextjs@5.1.5`.

**Pull request merged**
