### PR TITLE
chore(clerk-js): Add a descriptor for Invitation previews

### PR DESCRIPTION
**Pull request by EmmanouelaPothitou**
## Description
Add a descriptor for Invitation previews in OrganizationSwitcher component

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Comment by octoper** [comment]
!preview

**Comment by clerk-cookie** [comment]
Hey @octoper, your preview is currently deploying and should be available shortly.

| Status | Preview | Updated (UTC) |
| :-- | :-- | :-- |
| :cook: _Deploying..._ | [Inspect](https://javascript-preview-a7gi10tb5.clerkstage.dev) | May 14, 2024 10:00 AM |

**Review by anagstef — APPROVED** [review]
💯

**Review by dimkl — APPROVED** [review]

**Comment by octoper** [comment]
!preview

**Review by octoper — APPROVED** [review]
🔥

**Pull request merged**
