### PR TITLE
fix(clerk-js): Avoid depending on `count` as it can be zero but invitations may still exist

### PR DESCRIPTION
**Pull request by panteliselef**
## Description

**Background**: In order to provide a better UX, we are manually updating the cache where userInvitations are stored. This allows us to update the invitation in place and avoid layout shifts, if we would simply revalidate this would not be possible.

We are also manually updating `count` in the local cache in order to display the correct number of invitations available, without revalidating as this would cause a layout shift.

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Comment by octoper** [comment]
!preview

**Review by dimkl — COMMENTED** [review]
❓ what is the actual use case where we want to have count `0` with invitations?
If there is no case (product wise) i think we need to open a bug ticket to the backend team to fix this.

**Comment by clerk-cookie** [comment]
Hey @octoper, your preview is currently deploying and should be available shortly.

| Status | Preview | Updated (UTC) |
| :-- | :-- | :-- |
| :cook: _Deploying..._ | [Inspect](https://javascript-preview-gu3oscv38.clerkstage.dev) | Apr 02, 2024 01:38 PM |

**Comment by panteliselef** [comment]
> ❓ what is the actual use case where we want to have count `0` with invitations? If there is no case (product wise) i think we need to open a bug ticket to the backend team to fix this.

@dimkl I updated the description. Generally `count` is very useful, for this particular case and because we manually update the cache instead of revalidating we need to use this differently.

**Review by octoper — APPROVED** [review]
💯

**Comment by dimkl** [comment]
@panteliselef Is the `userInvitations` or `userSuggestions` paginated responses? If so, is the `count` related to the total count data of the response?
If the `count` is related to the total count of the paginated response, i think we still need to depend on that instead of the `length`. Wdyt?

**Pull request merged**
