### PR TITLE
feat(localizations): Add huHU localization

### PR DESCRIPTION
**Pull request by ezkomoly**
## Description
Added hungarian language

## Checklist

- [X] `npm test` runs as expected.
- [X] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [X] other: Localization

### CODE REVIEW

**Comment by ezkomoly** [comment]
I forgot to add the Changeset. Not sure, if I could do it at this point, or should I open a new PR ?

**Review by dimkl — COMMENTED** [review]
Hello @ezkomoly,
thank you for the contribution!! :) 
It seems that a few things are missing for this PR to allow us to merge it:
- export the `hu-HU.ts` from the localization package (need to export it from the index.ts)
- add a changelog entry for this (check the changeset-bot comment of this PR)

**Comment by dimkl** [comment]
@ezkomoly ignore it this time. We will add the changeset. :)

**Comment by ezkomoly** [comment]
> Hello @ezkomoly, thank you for the contribution!! :) It seems that a few things are missing for this PR to allow us to merge it:
> 
> * export the `hu-HU.ts` from the localization package (need to export it from the index.ts)
> * add a changelog entry for this (check the changeset-bot comment of this PR)

Thanks for adding the changeset! 
I exported huHU from the index.ts.

**Review by tmilewski — APPROVED** [review]
💯

**Pull request merged**
