### PR TITLE
Elef/sdk 1754 add open and onopenchange to userbutton and switcher

### PR DESCRIPTION
**Pull request by panteliselef**
## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Comment by panteliselef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @panteliselef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 1.1.6-snapshot.v5e93518 |
| @clerk/chrome-extension | 1.0.13-snapshot.v5e93518 |
| @clerk/clerk-js | 5.5.0-snapshot.v5e93518 |
| @clerk/elements | 0.4.6-snapshot.v5e93518 |
| @clerk/clerk-expo | 1.1.5-snapshot.v5e93518 |
| @clerk/express | 0.0.9-snapshot.v5e93518 |
| @clerk/fastify | 1.0.10-snapshot.v5e93518 |
| gatsby-plugin-clerk | 5.0.0-beta.45 |
| @clerk/nextjs | 5.0.13-snapshot.v5e93518 |
| @clerk/clerk-react | 5.1.1-snapshot.v5e93518 |
| @clerk/remix | 4.0.11-snapshot.v5e93518 |
| @clerk/clerk-sdk-node | 5.0.8-snapshot.v5e93518 |
| @clerk/shared | 2.2.0-snapshot.v5e93518 |
| @clerk/testing | 1.1.3-snapshot.v5e93518 |
| @clerk/themes | 2.1.7-snapshot.v5e93518 |
| @clerk/types | 4.5.0-snapshot.v5e93518 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/backend`
```sh
npm i @clerk/backend@1.1.6-snapshot.v5e93518 --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.0.13-snapshot.v5e93518 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.5.0-snapshot.v5e93518 --save-exact
```
`@clerk/elements`
```sh
npm i @clerk/elements@0.4.6-snapshot.v5e93518 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@1.1.5-snapshot.v5e93518 --save-exact
```
`@clerk/express`
```sh
npm i @clerk/express@0.0.9-snapshot.v5e93518 --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@1.0.10-snapshot.v5e93518 --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@5.0.0-beta.45 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@5.0.13-snapshot.v5e93518 --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@5.1.1-snapshot.v5e93518 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.0.11-snapshot.v5e93518 --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@5.0.8-snapshot.v5e93518 --save-exact
```
`@clerk/shared`
```sh
npm i @clerk/shared@2.2.0-snapshot.v5e93518 --save-exact
```
`@clerk/testing`
```sh
npm i @clerk/testing@1.1.3-snapshot.v5e93518 --save-exact
```
`@clerk/themes`
```sh
npm i @clerk/themes@2.1.7-snapshot.v5e93518 --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@4.5.0-snapshot.v5e93518 --save-exact
```

**Comment by clerk-cookie** [comment]
Hey @panteliselef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 1.1.6-snapshot.vf66cac0 |
| @clerk/chrome-extension | 1.0.13-snapshot.vf66cac0 |
| @clerk/clerk-js | 5.5.0-snapshot.vf66cac0 |
| @clerk/elements | 0.4.6-snapshot.vf66cac0 |
| @clerk/clerk-expo | 1.1.5-snapshot.vf66cac0 |
| @clerk/express | 0.0.9-snapshot.vf66cac0 |
| @clerk/fastify | 1.0.10-snapshot.vf66cac0 |
| gatsby-plugin-clerk | 5.0.0-beta.45 |
| @clerk/nextjs | 5.0.13-snapshot.vf66cac0 |
| @clerk/clerk-react | 5.1.1-snapshot.vf66cac0 |
| @clerk/remix | 4.0.11-snapshot.vf66cac0 |
| @clerk/clerk-sdk-node | 5.0.8-snapshot.vf66cac0 |
| @clerk/shared | 2.2.0-snapshot.vf66cac0 |
| @clerk/testing | 1.1.3-snapshot.vf66cac0 |
| @clerk/themes | 2.1.7-snapshot.vf66cac0 |
| @clerk/types | 4.5.0-snapshot.vf66cac0 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/backend`
```sh
npm i @clerk/backend@1.1.6-snapshot.vf66cac0 --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.0.13-snapshot.vf66cac0 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.5.0-snapshot.vf66cac0 --save-exact
```
`@clerk/elements`
```sh
npm i @clerk/elements@0.4.6-snapshot.vf66cac0 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@1.1.5-snapshot.vf66cac0 --save-exact
```
`@clerk/express`
```sh
npm i @clerk/express@0.0.9-snapshot.vf66cac0 --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@1.0.10-snapshot.vf66cac0 --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@5.0.0-beta.45 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@5.0.13-snapshot.vf66cac0 --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@5.1.1-snapshot.vf66cac0 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.0.11-snapshot.vf66cac0 --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@5.0.8-snapshot.vf66cac0 --save-exact
```
`@clerk/shared`
```sh
npm i @clerk/shared@2.2.0-snapshot.vf66cac0 --save-exact
```
`@clerk/testing`
```sh
npm i @clerk/testing@1.1.3-snapshot.vf66cac0 --save-exact
```
`@clerk/themes`
```sh
npm i @clerk/themes@2.1.7-snapshot.vf66cac0 --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@4.5.0-snapshot.vf66cac0 --save-exact
```

**Comment by panteliselef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @panteliselef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/chrome-extension | 1.0.15-snapshot.v7546a52 |
| @clerk/clerk-js | 5.6.0-snapshot.v7546a52 |
| @clerk/elements | 0.5.1-snapshot.v7546a52 |
| @clerk/clerk-expo | 1.1.7-snapshot.v7546a52 |
| @clerk/fastify | 1.0.12-snapshot.v7546a52 |
| gatsby-plugin-clerk | 5.0.0-beta.45 |
| @clerk/nextjs | 5.1.3-snapshot.v7546a52 |
| @clerk/clerk-react | 5.2.2-snapshot.v7546a52 |
| @clerk/remix | 4.0.13-snapshot.v7546a52 |
| @clerk/testing | 1.1.5-snapshot.v7546a52 |
| @clerk/themes | 2.1.8-snapshot.v7546a52 |
| @clerk/types | 4.6.0-snapshot.v7546a52 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.0.15-snapshot.v7546a52 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.6.0-snapshot.v7546a52 --save-exact
```
`@clerk/elements`
```sh
npm i @clerk/elements@0.5.1-snapshot.v7546a52 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@1.1.7-snapshot.v7546a52 --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@1.0.12-snapshot.v7546a52 --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@5.0.0-beta.45 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@5.1.3-snapshot.v7546a52 --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@5.2.2-snapshot.v7546a52 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.0.13-snapshot.v7546a52 --save-exact
```
`@clerk/testing`
```sh
npm i @clerk/testing@1.1.5-snapshot.v7546a52 --save-exact
```
`@clerk/themes`
```sh
npm i @clerk/themes@2.1.8-snapshot.v7546a52 --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@4.6.0-snapshot.v7546a52 --save-exact
```

**Comment by panteliselef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @panteliselef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/chrome-extension | 1.0.15-snapshot.v4a6989f |
| @clerk/clerk-js | 5.6.0-snapshot.v4a6989f |
| @clerk/elements | 0.5.1-snapshot.v4a6989f |
| @clerk/clerk-expo | 1.1.7-snapshot.v4a6989f |
| @clerk/fastify | 1.0.12-snapshot.v4a6989f |
| gatsby-plugin-clerk | 5.0.0-beta.45 |
| @clerk/nextjs | 5.1.3-snapshot.v4a6989f |
| @clerk/clerk-react | 5.2.2-snapshot.v4a6989f |
| @clerk/remix | 4.0.13-snapshot.v4a6989f |
| @clerk/testing | 1.1.5-snapshot.v4a6989f |
| @clerk/themes | 2.1.8-snapshot.v4a6989f |
| @clerk/types | 4.6.0-snapshot.v4a6989f |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.0.15-snapshot.v4a6989f --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.6.0-snapshot.v4a6989f --save-exact
```
`@clerk/elements`
```sh
npm i @clerk/elements@0.5.1-snapshot.v4a6989f --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@1.1.7-snapshot.v4a6989f --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@1.0.12-snapshot.v4a6989f --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@5.0.0-beta.45 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@5.1.3-snapshot.v4a6989f --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@5.2.2-snapshot.v4a6989f --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.0.13-snapshot.v4a6989f --save-exact
```
`@clerk/testing`
```sh
npm i @clerk/testing@1.1.5-snapshot.v4a6989f --save-exact
```
`@clerk/themes`
```sh
npm i @clerk/themes@2.1.8-snapshot.v4a6989f --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@4.6.0-snapshot.v4a6989f --save-exact
```

**Pull request closed without merging**
