### PR TITLE
chore(repo): Attempt to fix retheme build

### PR DESCRIPTION
**Pull request by nikospapcom**
## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Comment by nikospapcom** [comment]
!retheme

**Comment by nikospapcom** [comment]
!preview

**Comment by nikospapcom** [comment]
!preview

**Comment by nikospapcom** [comment]
!preview

**Comment by nikospapcom** [comment]
!preview

**Comment by nikospapcom** [comment]
!preview

**Comment by nikospapcom** [comment]
!preview

**Comment by clerk-cookie** [comment]
Hey @nikospapcom, your preview is currently deploying and should be available shortly.

| Status | Preview | Updated (UTC) |
| :-- | :-- | :-- |
| :cook: _Deploying..._ | [Inspect](https://javascript-preview-2ml98mupt.clerkstage.dev) | Nov 04, 2024 02:57 PM |

**Review by panteliselef — APPROVED** [review]

**Pull request merged**
