### PR TITLE
fix(backend): Make NFT not scan users directory

### PR DESCRIPTION
**Pull request by wobsoriano**
## Description

Please do not merge. This is a test PR to check if splitting and joining the `/users` base path will make `@vercel/nft` package skip scanning it

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Comment by wobsoriano** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @wobsoriano - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/astro | 1.3.0-snapshot.v5b5e672 |
| @clerk/backend | 1.10.0-snapshot.v5b5e672 |
| @clerk/chrome-extension | 1.3.2-snapshot.v5b5e672 |
| @clerk/clerk-js | 5.21.0-snapshot.v5b5e672 |
| @clerk/elements | 0.15.0-snapshot.v5b5e672 |
| @clerk/clerk-expo | 2.2.8-snapshot.v5b5e672 |
| @clerk/express | 0.0.37-snapshot.v5b5e672 |
| @clerk/fastify | 1.0.39-snapshot.v5b5e672 |
| @clerk/localizations | 3.0.0-snapshot.v5b5e672 |
| @clerk/nextjs | 5.5.0-snapshot.v5b5e672 |
| @clerk/clerk-react | 5.8.0-snapshot.v5b5e672 |
| @clerk/remix | 4.2.23-snapshot.v5b5e672 |
| @clerk/clerk-sdk-node | 5.0.36-snapshot.v5b5e672 |
| @clerk/shared | 2.7.0-snapshot.v5b5e672 |
| @clerk/tanstack-start | 0.3.6-snapshot.v5b5e672 |
| @clerk/testing | 1.2.19-snapshot.v5b5e672 |
| @clerk/themes | 2.1.28-snapshot.v5b5e672 |
| @clerk/types | 4.20.0-snapshot.v5b5e672 |
| @clerk/ui | 0.1.9-snapshot.v5b5e672 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/astro`
```sh
npm i @clerk/astro@1.3.0-snapshot.v5b5e672 --save-exact
```
`@clerk/backend`
```sh
npm i @clerk/backend@1.10.0-snapshot.v5b5e672 --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.3.2-snapshot.v5b5e672 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.21.0-snapshot.v5b5e672 --save-exact
```
`@clerk/elements`
```sh
npm i @clerk/elements@0.15.0-snapshot.v5b5e672 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@2.2.8-snapshot.v5b5e672 --save-exact
```
`@clerk/express`
```sh
npm i @clerk/express@0.0.37-snapshot.v5b5e672 --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@1.0.39-snapshot.v5b5e672 --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@3.0.0-snapshot.v5b5e672 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@5.5.0-snapshot.v5b5e672 --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@5.8.0-snapshot.v5b5e672 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.2.23-snapshot.v5b5e672 --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@5.0.36-snapshot.v5b5e672 --save-exact
```
`@clerk/shared`
```sh
npm i @clerk/shared@2.7.0-snapshot.v5b5e672 --save-exact
```
`@clerk/tanstack-start`
```sh
npm i @clerk/tanstack-start@0.3.6-snapshot.v5b5e672 --save-exact
```
`@clerk/testing`
```sh
npm i @clerk/testing@1.2.19-snapshot.v5b5e672 --save-exact
```
`@clerk/themes`
```sh
npm i @clerk/themes@2.1.28-snapshot.v5b5e672 --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@4.20.0-snapshot.v5b5e672 --save-exact
```
`@clerk/ui`
```sh
npm i @clerk/ui@0.1.9-snapshot.v5b5e672 --save-exact
```

**Comment by wobsoriano** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @wobsoriano - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/astro | 1.3.0-snapshot.v3ebc4fe |
| @clerk/backend | 1.10.0-snapshot.v3ebc4fe |
| @clerk/chrome-extension | 1.3.2-snapshot.v3ebc4fe |
| @clerk/clerk-js | 5.21.0-snapshot.v3ebc4fe |
| @clerk/elements | 0.15.0-snapshot.v3ebc4fe |
| @clerk/clerk-expo | 2.2.8-snapshot.v3ebc4fe |
| @clerk/express | 0.0.37-snapshot.v3ebc4fe |
| @clerk/fastify | 1.0.39-snapshot.v3ebc4fe |
| @clerk/localizations | 3.0.0-snapshot.v3ebc4fe |
| @clerk/nextjs | 5.5.0-snapshot.v3ebc4fe |
| @clerk/clerk-react | 5.8.0-snapshot.v3ebc4fe |
| @clerk/remix | 4.2.23-snapshot.v3ebc4fe |
| @clerk/clerk-sdk-node | 5.0.36-snapshot.v3ebc4fe |
| @clerk/shared | 2.7.0-snapshot.v3ebc4fe |
| @clerk/tanstack-start | 0.3.6-snapshot.v3ebc4fe |
| @clerk/testing | 1.2.19-snapshot.v3ebc4fe |
| @clerk/themes | 2.1.28-snapshot.v3ebc4fe |
| @clerk/types | 4.20.0-snapshot.v3ebc4fe |
| @clerk/ui | 0.1.9-snapshot.v3ebc4fe |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/astro`
```sh
npm i @clerk/astro@1.3.0-snapshot.v3ebc4fe --save-exact
```
`@clerk/backend`
```sh
npm i @clerk/backend@1.10.0-snapshot.v3ebc4fe --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.3.2-snapshot.v3ebc4fe --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.21.0-snapshot.v3ebc4fe --save-exact
```
`@clerk/elements`
```sh
npm i @clerk/elements@0.15.0-snapshot.v3ebc4fe --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@2.2.8-snapshot.v3ebc4fe --save-exact
```
`@clerk/express`
```sh
npm i @clerk/express@0.0.37-snapshot.v3ebc4fe --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@1.0.39-snapshot.v3ebc4fe --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@3.0.0-snapshot.v3ebc4fe --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@5.5.0-snapshot.v3ebc4fe --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@5.8.0-snapshot.v3ebc4fe --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.2.23-snapshot.v3ebc4fe --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@5.0.36-snapshot.v3ebc4fe --save-exact
```
`@clerk/shared`
```sh
npm i @clerk/shared@2.7.0-snapshot.v3ebc4fe --save-exact
```
`@clerk/tanstack-start`
```sh
npm i @clerk/tanstack-start@0.3.6-snapshot.v3ebc4fe --save-exact
```
`@clerk/testing`
```sh
npm i @clerk/testing@1.2.19-snapshot.v3ebc4fe --save-exact
```
`@clerk/themes`
```sh
npm i @clerk/themes@2.1.28-snapshot.v3ebc4fe --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@4.20.0-snapshot.v3ebc4fe --save-exact
```
`@clerk/ui`
```sh
npm i @clerk/ui@0.1.9-snapshot.v3ebc4fe --save-exact
```

**Pull request closed without merging**
