### PR TITLE
feat(clerk-js,types,localizations): Render "Restricted access" screen for restricted signup mode

### PR DESCRIPTION
**Pull request by nikospapcom**
## Description

When `sign_up.mode` is `restricted` we render the new `Restricted access` screen (screenshot 👇)
When `sign_up.mode` is `restricted` and `ticket` is presented then we render the signup screen as we're doing right now

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [x] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

Screenshot 2024-09-25 at 3 46 30 PM

### CODE REVIEW

**Review by panteliselef — APPROVED** [review]

**Review by octoper — APPROVED** [review]

**Comment by nikospapcom** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @nikospapcom - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/astro | 1.3.9-snapshot.v12963e8 |
| @clerk/backend | 1.13.5-snapshot.v12963e8 |
| @clerk/chrome-extension | 1.3.11-snapshot.v12963e8 |
| @clerk/clerk-js | 5.24.0-snapshot.v12963e8 |
| @clerk/elements | 0.15.7-snapshot.v12963e8 |
| @clerk/clerk-expo | 2.2.17-snapshot.v12963e8 |
| @clerk/express | 1.0.2-snapshot.v12963e8 |
| @clerk/fastify | 1.0.48-snapshot.v12963e8 |
| @clerk/localizations | 3.1.0-snapshot.v12963e8 |
| @clerk/nextjs | 5.6.3-snapshot.v12963e8 |
| @clerk/clerk-react | 5.9.4-snapshot.v12963e8 |
| @clerk/remix | 4.2.32-snapshot.v12963e8 |
| @clerk/clerk-sdk-node | 5.0.45-snapshot.v12963e8 |
| @clerk/shared | 2.8.4-snapshot.v12963e8 |
| @clerk/tanstack-start | 0.4.8-snapshot.v12963e8 |
| @clerk/testing | 1.3.6-snapshot.v12963e8 |
| @clerk/themes | 2.1.33-snapshot.v12963e8 |
| @clerk/types | 4.23.0-snapshot.v12963e8 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/astro`
```sh
npm i @clerk/astro@1.3.9-snapshot.v12963e8 --save-exact
```
`@clerk/backend`
```sh
npm i @clerk/backend@1.13.5-snapshot.v12963e8 --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.3.11-snapshot.v12963e8 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.24.0-snapshot.v12963e8 --save-exact
```
`@clerk/elements`
```sh
npm i @clerk/elements@0.15.7-snapshot.v12963e8 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@2.2.17-snapshot.v12963e8 --save-exact
```
`@clerk/express`
```sh
npm i @clerk/express@1.0.2-snapshot.v12963e8 --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@1.0.48-snapshot.v12963e8 --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@3.1.0-snapshot.v12963e8 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@5.6.3-snapshot.v12963e8 --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@5.9.4-snapshot.v12963e8 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.2.32-snapshot.v12963e8 --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@5.0.45-snapshot.v12963e8 --save-exact
```
`@clerk/shared`
```sh
npm i @clerk/shared@2.8.4-snapshot.v12963e8 --save-exact
```
`@clerk/tanstack-start`
```sh
npm i @clerk/tanstack-start@0.4.8-snapshot.v12963e8 --save-exact
```
`@clerk/testing`
```sh
npm i @clerk/testing@1.3.6-snapshot.v12963e8 --save-exact
```
`@clerk/themes`
```sh
npm i @clerk/themes@2.1.33-snapshot.v12963e8 --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@4.23.0-snapshot.v12963e8 --save-exact
```

**Comment by nikospapcom** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @nikospapcom - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/astro | 1.3.9-snapshot.v4f9daf5 |
| @clerk/backend | 1.13.5-snapshot.v4f9daf5 |
| @clerk/chrome-extension | 1.3.11-snapshot.v4f9daf5 |
| @clerk/clerk-js | 5.24.0-snapshot.v4f9daf5 |
| @clerk/elements | 0.15.7-snapshot.v4f9daf5 |
| @clerk/clerk-expo | 2.2.17-snapshot.v4f9daf5 |
| @clerk/express | 1.0.2-snapshot.v4f9daf5 |
| @clerk/fastify | 1.0.48-snapshot.v4f9daf5 |
| @clerk/localizations | 3.1.0-snapshot.v4f9daf5 |
| @clerk/nextjs | 5.6.3-snapshot.v4f9daf5 |
| @clerk/clerk-react | 5.9.4-snapshot.v4f9daf5 |
| @clerk/remix | 4.2.32-snapshot.v4f9daf5 |
| @clerk/clerk-sdk-node | 5.0.45-snapshot.v4f9daf5 |
| @clerk/shared | 2.8.4-snapshot.v4f9daf5 |
| @clerk/tanstack-start | 0.4.8-snapshot.v4f9daf5 |
| @clerk/testing | 1.3.6-snapshot.v4f9daf5 |
| @clerk/themes | 2.1.33-snapshot.v4f9daf5 |
| @clerk/types | 4.23.0-snapshot.v4f9daf5 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/astro`
```sh
npm i @clerk/astro@1.3.9-snapshot.v4f9daf5 --save-exact
```
`@clerk/backend`
```sh
npm i @clerk/backend@1.13.5-snapshot.v4f9daf5 --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.3.11-snapshot.v4f9daf5 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.24.0-snapshot.v4f9daf5 --save-exact
```
`@clerk/elements`
```sh
npm i @clerk/elements@0.15.7-snapshot.v4f9daf5 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@2.2.17-snapshot.v4f9daf5 --save-exact
```
`@clerk/express`
```sh
npm i @clerk/express@1.0.2-snapshot.v4f9daf5 --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@1.0.48-snapshot.v4f9daf5 --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@3.1.0-snapshot.v4f9daf5 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@5.6.3-snapshot.v4f9daf5 --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@5.9.4-snapshot.v4f9daf5 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.2.32-snapshot.v4f9daf5 --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@5.0.45-snapshot.v4f9daf5 --save-exact
```
`@clerk/shared`
```sh
npm i @clerk/shared@2.8.4-snapshot.v4f9daf5 --save-exact
```
`@clerk/tanstack-start`
```sh
npm i @clerk/tanstack-start@0.4.8-snapshot.v4f9daf5 --save-exact
```
`@clerk/testing`
```sh
npm i @clerk/testing@1.3.6-snapshot.v4f9daf5 --save-exact
```
`@clerk/themes`
```sh
npm i @clerk/themes@2.1.33-snapshot.v4f9daf5 --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@4.23.0-snapshot.v4f9daf5 --save-exact
```

**Pull request merged**
