### PR TITLE
feat(nextjs): Accept `redirectUrl` as option for `auth().protect()` #2329

### PR DESCRIPTION
**Pull request by panteliselef**
## Description

Backport of #2329

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/backend`
- [ ] `@clerk/chrome-extension`
- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [ ] `@clerk/localizations`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/remix`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/themes`
- [ ] `@clerk/types`
- [ ] `build/tooling/chore`

### CODE REVIEW

**Review by dimkl — APPROVED** [review]
🔧  Please add a description before merging.

**Comment by panteliselef** [comment]
!snapshot

**Comment by panteliselef** [comment]
The same PR for v5 fails for the E2E tests, need to investigate more before merging this one.
https://github.com/clerk/javascript/pull/2329

**Comment by panteliselef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @panteliselef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 0.36.0-snapshot.v3d9144d |
| @clerk/chrome-extension | 0.6.0-snapshot.v3d9144d |
| @clerk/clerk-js | 4.67.0-snapshot.v3d9144d |
| @clerk/clerk-expo | 0.19.25-snapshot.v3d9144d |
| @clerk/fastify | 0.6.27-snapshot.v3d9144d |
| gatsby-plugin-clerk | 4.4.29-snapshot.v3d9144d |
| @clerk/localizations | 1.26.13-snapshot.v3d9144d |
| @clerk/nextjs | 4.28.0-snapshot.v3d9144d |
| @clerk/clerk-react | 4.30.0-snapshot.v3d9144d |
| @clerk/remix | 3.1.11-snapshot.v3d9144d |
| @clerk/clerk-sdk-node | 4.13.2-snapshot.v3d9144d |
| @clerk/types | 3.60.0-snapshot.v3d9144d |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/backend`
```sh
npm i @clerk/backend@0.36.0-snapshot.v3d9144d --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@0.6.0-snapshot.v3d9144d --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@4.67.0-snapshot.v3d9144d --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@0.19.25-snapshot.v3d9144d --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@0.6.27-snapshot.v3d9144d --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@4.4.29-snapshot.v3d9144d --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@1.26.13-snapshot.v3d9144d --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@4.28.0-snapshot.v3d9144d --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@4.30.0-snapshot.v3d9144d --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@3.1.11-snapshot.v3d9144d --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@4.13.2-snapshot.v3d9144d --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@3.60.0-snapshot.v3d9144d --save-exact
```

**Pull request merged**
