### PR TITLE
fix(astro): ignore prerendered pages in middleware

### LINKED ISSUE #4639: Prerendered pages in Astro throw a warning when using clerkMiddleware
### Preliminary Checks

- [X] I have reviewed the documentation: https://clerk.com/docs

- [X] I have searched for existing issues: https://github.com/clerk/javascript/issues

- [X] I have not already reached out to Clerk support via email or Discord (if you have, no need to open an issue here)

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Clerk. Please ask questions in our Discord community: https://clerk.com/discord.

### Reproduction

https://github.com/learnwithjason/learnwithjason.dev-v2

### Publishable key

n/a

### Description

**Steps to reproduce:**

1. Add Clerk middleware to an Astro site
2. Load a page that has `export const prerender = true`

**Expected behavior:**

Prerendered pages should be ignored by the middleware since they can't depend on user data.

**Actual behavior:**

A warning is thrown by Astro because Clerk attempts to access headers on a prerendered page:

```
13:09:37 [WARN] `Astro.request.headers` is not available on prerendered pages. If you need access to request headers, make sure that the page is server rendered using `export const prerender = false;` or by setting `output` to `"server"` in your Astro config to make all your pages server rendered.
```

### Environment

```Shell
n/a
```

### PR DESCRIPTION
**Pull request by jlengstorf**
fixes #4639

## Checklist

- [x] `pnpm test` runs as expected.
- [ ] `pnpm build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [x] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Comment by tmilewski** [comment]
Thanks, @jlengstorf!

**Comment by wobsoriano** [comment]
Thanks @jlengstorf!

In case you still want to protect CSR pages, you can use the exported [stores](https://clerk.com/docs/references/astro/auth-store):

```html
---
export async function getStaticPaths() {
  // other code
}
---

<!-- other code -->

<script>
import { $authStore } from '@clerk/astro/client'

$authStore.subscribe((auth) => {
  if (auth.userId === undefined) {
    // loading
  } else if (auth.userId === null) {
    // redirect to page
  }
})
</script>
```

**Comment by mlafeldt** [comment]
As far as I know, `isPrerendered` will be added in Astro 5, right?

Right now, the property is called `_isPrerendered.`

**Comment by wobsoriano** [comment]
Is `main` branch v4? I think they ported `isPrerendered` to v4 [here](https://github.com/withastro/astro/blob/3a76353248009c1960344a4d2d28d56ccb50bade/packages/astro/src/core/render-context.ts#L310)

**Comment by mlafeldt** [comment]
> Thanks for this! Is `main` branch v4? I think they ported `isPrerendered` to v4 [here](https://github.com/withastro/astro/blob/3a76353248009c1960344a4d2d28d56ccb50bade/packages/astro/src/core/render-context.ts#L310)

Hm, I don't think so. I'm using Astro v4.16.16 and all I see is `_isPrerendered`.

```
❯ rg --no-ignore isPrerendered node_modules/astro
node_modules/astro/dist/actions/runtime/middleware.js
11:  if (context._isPrerendered) {

node_modules/astro/dist/core/render-context.js
95:    const isPrerendered = !serverLike || this.routeData.prerender;
104:    const apiContext = this.createAPIContext(props, isPrerendered);
185:  createAPIContext(props, isPrerendered) {
198:      _isPrerendered: isPrerendered

node_modules/astro/dist/core/render-context.d.ts
46:    createAPIContext(props: APIContext['props'], isPrerendered: boolean): APIContext;
```

**Comment by mlafeldt** [comment]
> Okay, I can confirm it's still `_isPrerendered` in latest v4 version. Will do a follow up PR.

@wobsoriano Cool. Something like this should work for all versions:

```ts
const isPrerendered = (context: any) => context._isPrerendered || context.isPrerendered
```

**Comment by jlengstorf** [comment]
sorry about that! I'm using Astro 5 😅

**Pull request merged**
