### PR TITLE
feat(backend): Also export token-related errors

### PR DESCRIPTION
**Pull request by flawnn**
## Checklist

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [x] other: Developer Experience

## Packages affected

- [x] `@clerk/backend`
- [ ] `@clerk/chrome-extension`
- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [ ] `@clerk/localizations`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/remix`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/themes`
- [ ] `@clerk/types`
- [ ] `build/tooling/chore`

### CODE REVIEW

**Review by tmilewski — APPROVED** [review]
@flawnn Thanks for your PR! Looks good to me! Would you mind [adding a changeset](https://github.com/clerkinc/javascript/blob/main/docs/CONTRIBUTING.md#changesets)?

**Comment by flawnn** [comment]
@tmilewski Done!

**Review by nikosdouvlis — CHANGES_REQUESTED** [review]
Hello @flawnn :)
This PR makes total sense to me, however, it also exposes a few internal errors that should probably remain internal for the time being.

Could you please share more details about your use case so we can better understand the changes we need to make?

**Comment by LekoArts** [comment]
Please also add a description to your PR. Thanks!

**Comment by flawnn** [comment]
> Hello @flawnn :) This PR makes total sense to me, however, it also exposes a few internal errors that should probably remain internal for the time being.
> 
> Could you please share more details about your use case so we can better understand the changes we need to make?

Hey! The reason why I was suggesting this PR was that I wanted to be able to catch JWT Verification errors when working with `verifyJwt`. As an example here a code snippet:

```javascript
try {
    let v = await verifyJwt(authHeader.split(" ")[1], {} as VerifyJwtOptions);

    next();
  } catch (e) {
    if (e instanceof TokenVerificationError) {
      return res.status(401).send("Token has expired");
    }
    return res.status(401).send("Invalid token");
  }
```

Maybe as a reason why I even decided doing that, is that the Clerk Middleware for Express actually just throws an error and doesn't pass that error on to following middlewares when decoding the JWT Token (in some cases). One case was, when the JWT Token expired. The problem with not passing it on to following middlewares is obviously that it doesn't allow for custom error handling.

**Comment by nikosdouvlis** [comment]
@flawnn, many thanks for the contribution and inciting an internal discussion about this!
I'm going to close this PR as it targets `main` which is the development branch of our next major release (v5)
@tmilewski will be backporting the change into v4 (the current version of our packages) - you can track the progress here: https://github.com/clerk/javascript/pull/2189 

Thank you :)

**Pull request closed without merging**
