### PR TITLE
fix: handle ppr error message refactor

### PR DESCRIPTION
**Pull request by ceIia**
## Description

in a [pull request introduced last january](https://github.com/vercel/next.js/commit/3008af6b0e7b2c8aadd986bdcbce5bad6c39ccc8#diff-20c354509ae1e93e143d91b67b75e3df592c38b7d1ec6ccf7c4a2f72b32ab17d) in next.js (`dynamic-rendering.ts:153`), the message passed in `React.unstable_postpone` thrown for PPR bailout was changed, meaning the check implemented by #2518 was not enough anymore, and the bailout was not being rethrown anymore, breaking next.js builds using ppr, and probably other issues. 

i've updated it to match the latest version, but kept the old check for the sake of not causing a breaking change.

to test:
- run a next.js build on an app that uses ppr with the latest version of @clerk/nextjs ([should fail](https://gist.github.com/ceIia/dacd8c2fe3f0363278bc4dff5f4a4004))
- run another build with this pr (shouldn't fail anymore)

## Checklist

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [x] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

### CODE REVIEW

**Review by dimkl — APPROVED** [review]

**Comment by dimkl** [comment]
Nice work @ceIia 🎉  and thank you for the contribution!

**Comment by ceIia** [comment]
is there something i can do to fix the failing check @dimkl? i'm not 100% sure of why it broke

**Comment by dimkl** [comment]
@ceIia we are facing an issue with the integration tests failing for a forked PR because the GH secrets are not shared. I will let you know about the progress in the next couple of hours.

**Review by nikosdouvlis — APPROVED** [review]
This makes total sense to me. Thank you @ceIia

**Pull request merged**
